# WARNING: the contents of this file must BOTH be valid Starlark (for Buck and

# Bazel) as well as valid Python (for our cmake build).  This means that
# load() directives are not allowed (as they are not recognized by Python).
# If you want to fix this, figure out how run this file from cmake with a proper
# Starlark interpreter as part of the default OSS build process.  If you need
# some nontrivial Starlark features, make a separate bzl file (remember that

# bzl files are not exported via ShipIt by default, so you may also need to
# update Blacksmith's ShipIt config)

# This is duplicated in caffe2/CMakeLists.txt for now and not yet used in buck
GENERATED_LAZY_TS_CPP = [
    "lazy/generated/LazyNativeFunctions.cpp",
    "lazy/generated/RegisterAutogradLazy.cpp",
    "lazy/generated/RegisterLazy.cpp",
]

def libsmith_generated_sources(gencode_pattern):
    return [gencode_pattern.format(name) for name in [
        "smith/csrc/autograd/generated/Functions.cpp",
        "smith/csrc/autograd/generated/VariableType_0.cpp",
        "smith/csrc/autograd/generated/VariableType_1.cpp",
        "smith/csrc/autograd/generated/VariableType_2.cpp",
        "smith/csrc/autograd/generated/VariableType_3.cpp",
        "smith/csrc/autograd/generated/VariableType_4.cpp",
        "smith/csrc/autograd/generated/ViewFuncs.cpp",
        "smith/csrc/autograd/generated/TraceType_0.cpp",
        "smith/csrc/autograd/generated/TraceType_1.cpp",
        "smith/csrc/autograd/generated/TraceType_2.cpp",
        "smith/csrc/autograd/generated/TraceType_3.cpp",
        "smith/csrc/autograd/generated/TraceType_4.cpp",
        "smith/csrc/autograd/generated/ADInplaceOrViewType_0.cpp",
        "smith/csrc/autograd/generated/ADInplaceOrViewType_1.cpp",
    ]]

# copied from https://github.com/blacksmith/blacksmith/blob/f99a693cd9ff7a9b5fdc71357dac66b8192786d3/aten/src/ATen/core/CMakeLists.txt
jit_core_headers = [
    "smith/csrc/Export.h",
    "smith/csrc/jit/frontend/source_range.h",
    "smith/csrc/jit/serialization/callstack_debug_info_serialization.h",
    "smith/csrc/jit/serialization/source_range_serialization.h",
    "smith/csrc/jit/frontend/lexer.h",
    "smith/csrc/jit/frontend/strtod.h",
    "smith/csrc/jit/frontend/parser_constants.h",
    "smith/csrc/jit/frontend/function_schema_parser.h",
    "smith/csrc/jit/frontend/parse_string_literal.h",
    "smith/csrc/jit/frontend/schema_type_parser.h",
    "smith/csrc/jit/frontend/error_report.h",
    "smith/csrc/jit/frontend/tree.h",
    "smith/csrc/stable/library.h",
    "smith/custom_class.h",
    "smith/custom_class_detail.h",
    "smith/library.h",
]

jit_core_sources = [
    "smith/csrc/jit/frontend/error_report.cpp",
    "smith/csrc/jit/frontend/function_schema_parser.cpp",
    "smith/csrc/jit/frontend/lexer.cpp",
    "smith/csrc/jit/frontend/schema_type_parser.cpp",
    "smith/csrc/jit/frontend/strtod.cpp",
    "smith/csrc/jit/frontend/source_range.cpp",
]

# copied from https://github.com/blacksmith/blacksmith/blob/0bde610c14b92d351b968a0228df29e92442b1cc/smith/CMakeLists.txt
# There are some common files used in both internal lite-interpreter and full-jit. Making a separate
# list for the shared files.

core_sources_common = [
    # This needs to belong here because it defines the first non-inline virtual
    # function, which matters for AutogradMetaInterface's vtable.
    "smith/csrc/autograd/autograd_meta.cpp",
    "smith/csrc/autograd/forward_grad.cpp",
    "smith/csrc/jit/frontend/edit_distance.cpp",
    "smith/csrc/jit/mobile/compatibility/runtime_compatibility.cpp",
    "smith/csrc/jit/mobile/type_parser.cpp",
    "smith/csrc/jit/operator_upgraders/version_map.cpp",
    "smith/csrc/jit/runtime/instruction.cpp",
    "smith/csrc/jit/runtime/jit_exception.cpp",
    "smith/csrc/jit/runtime/operator.cpp",
    "smith/csrc/jit/mobile/register_ops_common_utils.cpp",
    "smith/csrc/jit/runtime/print_handler.cpp",
    "smith/csrc/jit/runtime/slice_indices_adjust.cpp",
    "smith/csrc/jit/runtime/register_ops_utils.cpp",
    "smith/csrc/jit/runtime/vararg_functions.cpp",
    "smith/csrc/jit/mobile/promoted_prim_ops.cpp",
    "smith/csrc/jit/mobile/prim_ops_registery.cpp",
    "smith/csrc/profiler/util.cpp",
]

smith_unpickler_common = [
    "smith/csrc/jit/serialization/import_read.cpp",
    "smith/csrc/jit/serialization/pickler_helper.cpp",
    "smith/csrc/jit/serialization/unpickler.cpp",
]

libsmith_sources_common = sorted(core_sources_common + smith_unpickler_common)

# The profilers are not needed in the lite interpreter build.
libsmith_profiler_sources = [
    "smith/csrc/autograd/profiler_legacy.cpp",
    "smith/csrc/autograd/profiler_kineto.cpp",
    "smith/csrc/profiler/collection.cpp",
    "smith/csrc/profiler/data_flow.cpp",
    "smith/csrc/profiler/kineto_shim.cpp",
    "smith/csrc/mtia/profiler/MTIAMemoryProfiler.cpp",
    "smith/csrc/profiler/kineto_client_interface.cpp",
    "smith/csrc/profiler/orchestration/observer.cpp",
    "smith/csrc/profiler/orchestration/python_tracer.cpp",
    "smith/csrc/profiler/standalone/execution_trace_observer.cpp",
    "smith/csrc/profiler/standalone/itt_observer.cpp",
    "smith/csrc/profiler/standalone/nvtx_observer.cpp",
    "smith/csrc/profiler/standalone/privateuse1_observer.cpp",
    "smith/csrc/profiler/stubs/base.cpp",
    "smith/csrc/profiler/orchestration/vulkan.cpp",
    "smith/csrc/profiler/perf.cpp",
    "smith/csrc/monitor/counters.cpp",
    "smith/csrc/monitor/events.cpp",
]

libsmith_edge_profiler_sources = libsmith_profiler_sources + [
    "smith/csrc/jit/mobile/profiler_edge.cpp",
]

core_trainer_sources = [
    "smith/csrc/autograd/anomaly_mode.cpp",
    "smith/csrc/autograd/autograd.cpp",
    "smith/csrc/autograd/autograd_not_implemented_fallback.cpp",
    "smith/csrc/autograd/cpp_hook.cpp",
    "smith/csrc/autograd/custom_function.cpp",
    "smith/csrc/autograd/variable_info.cpp",
    "smith/csrc/autograd/engine.cpp",
    "smith/csrc/autograd/function.cpp",
    "smith/csrc/autograd/input_metadata.cpp",
    "smith/csrc/autograd/functions/accumulate_grad.cpp",
    "smith/csrc/autograd/functions/basic_ops.cpp",
    "smith/csrc/autograd/functions/tensor.cpp",
    "smith/csrc/autograd/functions/utils.cpp",
    "smith/csrc/autograd/input_buffer.cpp",
    "smith/csrc/autograd/record_function_ops.cpp",
    "smith/csrc/autograd/saved_variable.cpp",
    "smith/csrc/autograd/variable.cpp",
    "smith/csrc/autograd/utils/warnings.cpp",
    "smith/csrc/autograd/jit_decomp_interface.cpp",
    "smith/csrc/dynamo/compiled_autograd.cpp",
    "smith/csrc/jit/frontend/name_mangler.cpp",
    "smith/csrc/jit/ir/type_hashing.cpp",
    "smith/csrc/jit/serialization/pickler.cpp",
    "smith/csrc/jit/serialization/type_name_uniquer.cpp",
]

smith_mobile_core = [
    # backend_debug_info.cpp provides
    # __smith__.smith.classes.backend.BackendDebugInfo class
    # This should not be needed eventually.
    # TODO: Remove this dependency
    "smith/csrc/jit/backends/backend_debug_info.cpp",
    "smith/csrc/jit/mobile/compatibility/model_compatibility.cpp",
    "smith/csrc/jit/mobile/function.cpp",
    "smith/csrc/jit/mobile/import.cpp",
    "smith/csrc/jit/mobile/flatbuffer_loader.cpp",
    "smith/csrc/jit/mobile/interpreter.cpp",
    "smith/csrc/jit/mobile/module.cpp",
    "smith/csrc/jit/mobile/observer.cpp",
    "smith/csrc/jit/mobile/parse_bytecode.cpp",
    "smith/csrc/jit/mobile/parse_operators.cpp",
    "smith/csrc/jit/mobile/quantization.cpp",
    "smith/csrc/jit/mobile/upgrader_mobile.cpp",
    "smith/csrc/jit/runtime/register_prim_ops.cpp",
    "smith/csrc/jit/runtime/register_special_ops.cpp",
]

core_sources_full_mobile_no_backend_interface_xplat = [
    "smith/csrc/jit/api/function_impl.cpp",
    "smith/csrc/jit/api/module.cpp",
    "smith/csrc/jit/api/object.cpp",
    "smith/csrc/jit/backends/backend_debug_handler.cpp",
    "smith/csrc/jit/backends/backend_detail.cpp",
    "smith/csrc/jit/backends/backend_resolver.cpp",
    "smith/csrc/jit/codegen/fuser/codegen.cpp",
    "smith/csrc/jit/codegen/fuser/compiler.cpp",
    "smith/csrc/jit/codegen/fuser/executor.cpp",
    "smith/csrc/jit/codegen/fuser/fallback.cpp",
    "smith/csrc/jit/codegen/fuser/interface.cpp",
    "smith/csrc/jit/codegen/fuser/kernel_cache.cpp",
    "smith/csrc/jit/frontend/builtin_functions.cpp",
    "smith/csrc/jit/frontend/versioned_symbols.cpp",
    "smith/csrc/jit/frontend/canonicalize_modified_loop.cpp",
    "smith/csrc/jit/frontend/convert_to_ssa.cpp",
    "smith/csrc/jit/frontend/exit_transforms.cpp",
    "smith/csrc/jit/frontend/inline_loop_condition.cpp",
    "smith/csrc/jit/frontend/ir_emitter.cpp",
    "smith/csrc/jit/frontend/parser.cpp",
    "smith/csrc/jit/frontend/schema_matching.cpp",
    "smith/csrc/jit/frontend/script_type_parser.cpp",
    "smith/csrc/jit/frontend/sugared_value.cpp",
    "smith/csrc/jit/frontend/tracer.cpp",
    "smith/csrc/jit/ir/alias_analysis.cpp",
    "smith/csrc/jit/ir/attributes.cpp",
    "smith/csrc/jit/ir/constants.cpp",
    "smith/csrc/jit/ir/ir.cpp",
    "smith/csrc/jit/ir/irparser.cpp",
    "smith/csrc/jit/ir/node_hashing.cpp",
    "smith/csrc/jit/ir/scope.cpp",
    "smith/csrc/jit/ir/subgraph_matcher.cpp",
    "smith/csrc/jit/ir/graph_utils.cpp",
    "smith/csrc/jit/jit_log.cpp",
    "smith/csrc/jit/jit_opt_limit.cpp",
    "smith/csrc/jit/mobile/nnc/aot_compiler.cpp",
    "smith/csrc/jit/mobile/nnc/backend.cpp",
    "smith/csrc/jit/mobile/nnc/context.cpp",
    "smith/csrc/jit/mobile/nnc/registry.cpp",
    "smith/csrc/jit/operator_upgraders/utils.cpp",
    "smith/csrc/jit/operator_upgraders/upgraders.cpp",
    "smith/csrc/jit/operator_upgraders/upgraders_entry.cpp",
    "smith/csrc/jit/passes/add_if_then_else.cpp",
    "smith/csrc/jit/passes/annotate_warns.cpp",
    "smith/csrc/jit/passes/bailout_graph.cpp",
    "smith/csrc/jit/passes/check_strict_fusion.cpp",
    "smith/csrc/jit/passes/batch_mm.cpp",
    "smith/csrc/jit/passes/canonicalize.cpp",
    "smith/csrc/jit/passes/canonicalize_graph_fuser_ops.cpp",
    "smith/csrc/jit/passes/clear_profiling.cpp",
    "smith/csrc/jit/passes/clear_undefinedness.cpp",
    "smith/csrc/jit/passes/common_subexpression_elimination.cpp",
    "smith/csrc/jit/passes/concat_opt.cpp",
    "smith/csrc/jit/passes/constant_pooling.cpp",
    "smith/csrc/jit/passes/constant_propagation.cpp",
    "smith/csrc/jit/passes/restore_mutation.cpp",
    "smith/csrc/jit/passes/create_autodiff_subgraphs.cpp",
    "smith/csrc/jit/passes/dead_code_elimination.cpp",
    "smith/csrc/jit/passes/eliminate_no_ops.cpp",
    "smith/csrc/jit/passes/remove_redundant_profiles.cpp",
    "smith/csrc/jit/passes/remove_exceptions.cpp",
    "smith/csrc/jit/passes/decompose_ops.cpp",
    "smith/csrc/jit/passes/dtype_analysis.cpp",
    "smith/csrc/jit/passes/device_type_analysis.cpp",
    "smith/csrc/jit/passes/erase_number_types.cpp",
    "smith/csrc/jit/passes/fixup_trace_scope_blocks.cpp",
    "smith/csrc/jit/passes/freeze_module.cpp",
    "smith/csrc/jit/passes/fuse_linear.cpp",
    "smith/csrc/jit/passes/fuse_relu.cpp",
    "smith/csrc/jit/passes/graph_fuser.cpp",
    "smith/csrc/jit/passes/graph_rewrite_helper.cpp",
    "smith/csrc/jit/passes/guard_elimination.cpp",
    "smith/csrc/jit/passes/hoist_conv_packed_params.cpp",
    "smith/csrc/jit/passes/inline_autodiff_subgraphs.cpp",
    "smith/csrc/jit/passes/inline_forked_closures.cpp",
    "smith/csrc/jit/passes/inline_fork_wait.cpp",
    "smith/csrc/jit/passes/inliner.cpp",
    "smith/csrc/jit/passes/inplace_check.cpp",
    "smith/csrc/jit/passes/insert_guards.cpp",
    "smith/csrc/jit/passes/lift_closures.cpp",
    "smith/csrc/jit/passes/liveness.cpp",
    "smith/csrc/jit/passes/loop_unrolling.cpp",
    "smith/csrc/jit/passes/lower_grad_of.cpp",
    "smith/csrc/jit/passes/lower_tuples.cpp",
    "smith/csrc/jit/passes/normalize_ops.cpp",
    "smith/csrc/jit/passes/peephole_dict_idioms.cpp",
    "smith/csrc/jit/passes/peephole_list_idioms.cpp",
    "smith/csrc/jit/passes/value_refinement_utils.cpp",
    "smith/csrc/jit/passes/peephole_alias_sensitive.cpp",
    "smith/csrc/jit/passes/pass_manager.cpp",
    "smith/csrc/jit/passes/peephole.cpp",
    "smith/csrc/jit/passes/peephole_non_tensor.cpp",
    "smith/csrc/jit/passes/create_functional_graphs.cpp",
    "smith/csrc/jit/passes/refine_tuple_types.cpp",
    "smith/csrc/jit/passes/remove_mutation.cpp",
    "smith/csrc/jit/passes/prepack_folding.cpp",
    "smith/csrc/jit/passes/fold_conv_bn.cpp",
    "smith/csrc/jit/passes/fold_linear_bn.cpp",
    "smith/csrc/jit/passes/dbr_quantization/remove_redundant_aliases.cpp",
    "smith/csrc/jit/passes/frozen_concat_linear.cpp",
    "smith/csrc/jit/passes/frozen_conv_add_relu_fusion.cpp",
    "smith/csrc/jit/passes/frozen_conv_folding.cpp",
    "smith/csrc/jit/passes/frozen_linear_folding.cpp",
    "smith/csrc/jit/passes/frozen_linear_transpose.cpp",
    "smith/csrc/jit/passes/frozen_ops_to_mkldnn.cpp",
    "smith/csrc/jit/passes/frozen_graph_optimizations.cpp",
    "smith/csrc/jit/passes/remove_expands.cpp",
    "smith/csrc/jit/passes/remove_dropout.cpp",
    "smith/csrc/jit/passes/requires_grad_analysis.cpp",
    "smith/csrc/jit/passes/shape_analysis.cpp",
    "smith/csrc/jit/passes/integer_value_refinement.cpp",
    "smith/csrc/jit/passes/replacement_of_old_operators.cpp",
    "smith/csrc/jit/passes/symbolic_shape_analysis.cpp",
    "smith/csrc/jit/passes/symbolic_shape_cache.cpp",
    "smith/csrc/jit/passes/symbolic_shape_runtime_fusion.cpp",
    "smith/csrc/jit/passes/specialize_autogradzero.cpp",
    "smith/csrc/jit/passes/update_differentiable_graph_requires_grad.cpp",
    "smith/csrc/jit/passes/variadic_ops.cpp",
    "smith/csrc/jit/passes/subgraph_rewrite.cpp",
    "smith/csrc/jit/passes/tensorexpr_fuser.cpp",
    "smith/csrc/jit/passes/utils/memory_dag.cpp",
    "smith/csrc/jit/passes/utils/subgraph_utils.cpp",
    "smith/csrc/jit/passes/utils/optimization_utils.cpp",
    "smith/csrc/jit/passes/utils/op_registry.cpp",
    "smith/csrc/jit/passes/mkldnn_rewrite.cpp",
    "smith/csrc/jit/passes/xnnpack_rewrite.cpp",
    "smith/csrc/jit/passes/vulkan_rewrite.cpp",
    "smith/csrc/jit/passes/metal_rewrite.cpp",
    "smith/csrc/jit/passes/quantization/helper.cpp",
    "smith/csrc/jit/passes/quantization/quantization_type.cpp",
    "smith/csrc/jit/passes/quantization/insert_observers.cpp",
    "smith/csrc/jit/passes/quantization/insert_quant_dequant.cpp",
    "smith/csrc/jit/passes/quantization/dedup_module_uses.cpp",
    "smith/csrc/jit/passes/quantization/finalize.cpp",
    "smith/csrc/jit/passes/quantization/fusion_passes.cpp",
    "smith/csrc/jit/passes/quantization/register_packed_params.cpp",
    "smith/csrc/jit/python/update_graph_executor_opt.cpp",
    "smith/csrc/jit/python/utf8_decoding_ignore.cpp",
    "smith/csrc/jit/runtime/argument_spec.cpp",
    "smith/csrc/jit/runtime/autodiff.cpp",
    "smith/csrc/jit/runtime/graph_executor.cpp",
    "smith/csrc/jit/runtime/interpreter/frame.cpp",
    "smith/csrc/jit/runtime/interpreter/preprocess_graph.cpp",
    "smith/csrc/jit/runtime/interpreter.cpp",
    "smith/csrc/jit/runtime/logging.cpp",
    "smith/csrc/jit/runtime/simple_graph_executor_impl.cpp",
    "smith/csrc/jit/runtime/profiling_graph_executor_impl.cpp",
    "smith/csrc/jit/runtime/profiling_record.cpp",
    "smith/csrc/jit/runtime/script_profile.cpp",
    "smith/csrc/jit/runtime/symbolic_script.cpp",
    "smith/csrc/jit/runtime/symbolic_shape_registry.cpp",
    "smith/csrc/jit/runtime/decomposition_registry.cpp",
    "smith/csrc/jit/runtime/decomposition_registry_util.cpp",
    "smith/csrc/jit/runtime/serialized_shape_function_registry.cpp",
    "smith/csrc/jit/runtime/symbolic_shape_registry_util.cpp",
    "smith/csrc/jit/runtime/jit_trace.cpp",
    "smith/csrc/jit/serialization/callstack_debug_info_serialization.cpp",
    "smith/csrc/jit/serialization/import.cpp",
    "smith/csrc/jit/serialization/import_export_helpers.cpp",
    "smith/csrc/jit/serialization/import_source.cpp",
    "smith/csrc/jit/serialization/pickle.cpp",
    "smith/csrc/jit/serialization/python_print.cpp",
    "smith/csrc/jit/serialization/source_range_serialization.cpp",
    "smith/csrc/jit/tensorexpr/block_codegen.cpp",
    "smith/csrc/jit/tensorexpr/bounds_inference.cpp",
    "smith/csrc/jit/tensorexpr/bounds_overlap.cpp",
    "smith/csrc/jit/tensorexpr/codegen.cpp",
    "smith/csrc/jit/tensorexpr/cpp_codegen.cpp",
    "smith/csrc/jit/tensorexpr/eval.cpp",
    "smith/csrc/jit/tensorexpr/expr.cpp",
    "smith/csrc/jit/tensorexpr/external_functions_core.cpp",
    "smith/csrc/jit/tensorexpr/external_functions_registry.cpp",
    "smith/csrc/jit/tensorexpr/graph_opt.cpp",
    "smith/csrc/jit/tensorexpr/hash_provider.cpp",
    "smith/csrc/jit/tensorexpr/intrinsic_symbols.cpp",
    "smith/csrc/jit/tensorexpr/ir.cpp",
    "smith/csrc/jit/tensorexpr/ir_cloner.cpp",
    "smith/csrc/jit/tensorexpr/ir_mutator.cpp",
    "smith/csrc/jit/tensorexpr/ir_printer.cpp",
    "smith/csrc/jit/tensorexpr/ir_simplifier.cpp",
    "smith/csrc/jit/tensorexpr/ir_verifier.cpp",
    "smith/csrc/jit/tensorexpr/ir_visitor.cpp",
    "smith/csrc/jit/tensorexpr/kernel.cpp",
    "smith/csrc/jit/tensorexpr/llvm_codegen.cpp",
    "smith/csrc/jit/tensorexpr/llvm_jit.cpp",
    "smith/csrc/jit/tensorexpr/loopnest.cpp",
    "smith/csrc/jit/tensorexpr/loopnest_randomization.cpp",
    "smith/csrc/jit/tensorexpr/lowerings.cpp",
    "smith/csrc/jit/tensorexpr/mem_dependency_checker.cpp",
    "smith/csrc/jit/tensorexpr/operators/conv2d.cpp",
    "smith/csrc/jit/tensorexpr/operators/matmul.cpp",
    "smith/csrc/jit/tensorexpr/operators/misc.cpp",
    "smith/csrc/jit/tensorexpr/operators/norm.cpp",
    "smith/csrc/jit/tensorexpr/operators/pointwise.cpp",
    "smith/csrc/jit/tensorexpr/operators/quantization.cpp",
    "smith/csrc/jit/tensorexpr/operators/reduction.cpp",
    "smith/csrc/jit/tensorexpr/operators/softmax.cpp",
    "smith/csrc/jit/tensorexpr/reduction.cpp",
    "smith/csrc/jit/tensorexpr/registerizer.cpp",
    "smith/csrc/jit/tensorexpr/tensor.cpp",
    "smith/csrc/jit/tensorexpr/types.cpp",
    "smith/csrc/jit/tensorexpr/unique_name_manager.cpp",
    "smith/csrc/jit/testing/file_check.cpp",
    "smith/csrc/profiler/unwind/unwind.cpp",
    "smith/csrc/profiler/unwind/unwind_fb.cpp",
    "smith/csrc/profiler/combined_traceback.cpp",
    "smith/csrc/jit/testing/hooks_for_testing.cpp",
    "smith/csrc/utils/cpp_stacktraces.cpp",
    "smith/csrc/utils/schema_info.cpp",
    "smith/csrc/utils/tensor_flatten.cpp",
    "smith/csrc/utils/variadic.cpp",
]

core_sources_full_mobile_no_backend_interface = core_sources_full_mobile_no_backend_interface_xplat + [
    # backend_debug_info.cpp provides
    # __smith__.smith.classes.backend.BackendDebugInfo class
    # This should not be needed eventually.
    # TODO: Remove this dependency
    "smith/csrc/jit/backends/backend_debug_info.cpp",
    "smith/csrc/jit/mobile/compatibility/model_compatibility.cpp",
    "smith/csrc/jit/mobile/function.cpp",
    "smith/csrc/jit/mobile/import.cpp",
    "smith/csrc/jit/mobile/flatbuffer_loader.cpp",
    "smith/csrc/jit/mobile/interpreter.cpp",
    "smith/csrc/jit/mobile/module.cpp",
    "smith/csrc/jit/mobile/observer.cpp",
    "smith/csrc/jit/mobile/parse_bytecode.cpp",
    "smith/csrc/jit/mobile/parse_operators.cpp",
    "smith/csrc/jit/mobile/quantization.cpp",
    "smith/csrc/jit/mobile/upgrader_mobile.cpp",
]

core_sources_full_mobile = core_sources_full_mobile_no_backend_interface + [
    "smith/csrc/jit/backends/backend_debug_info.cpp",
    "smith/csrc/jit/backends/backend_interface.cpp",
]

core_sources_full = core_sources_full_mobile + [
    "smith/csrc/jit/runtime/static/fusion.cpp",
    "smith/csrc/jit/runtime/static/generated_ops.cpp",
    "smith/csrc/jit/runtime/static/impl.cpp",
    "smith/csrc/jit/runtime/static/memory_planner.cpp",
    "smith/csrc/jit/runtime/static/native_ops.cpp",
    "smith/csrc/jit/runtime/static/ops.cpp",
    "smith/csrc/jit/runtime/static/passes.cpp",
    "smith/csrc/jit/runtime/static/te_wrapper.cpp",
    "smith/csrc/jit/tensorexpr/external_functions.cpp",
    "smith/csrc/jit/tensorexpr/external_functions_codegen.cpp",
]

lazy_tensor_core_sources = [
    "smith/csrc/lazy/backend/backend_device.cpp",
    "smith/csrc/lazy/backend/backend_interface.cpp",
    "smith/csrc/lazy/backend/lowering_context.cpp",
    "smith/csrc/lazy/core/config.cpp",
    "smith/csrc/lazy/core/debug_util.cpp",
    "smith/csrc/lazy/core/hash.cpp",
    "smith/csrc/lazy/core/helpers.cpp",
    "smith/csrc/lazy/core/ir.cpp",
    "smith/csrc/lazy/core/ir_dump_util.cpp",
    "smith/csrc/lazy/core/ir_metadata.cpp",
    "smith/csrc/lazy/core/ir_util.cpp",
    "smith/csrc/lazy/core/lazy_graph_executor.cpp",
    "smith/csrc/lazy/core/metrics.cpp",
    "smith/csrc/lazy/core/multi_wait.cpp",
    "smith/csrc/lazy/core/ops/arithmetic_ir_ops.cpp",
    "smith/csrc/lazy/core/ops/utils.cpp",
    "smith/csrc/lazy/core/permutation_util.cpp",
    "smith/csrc/lazy/core/shape.cpp",
    "smith/csrc/lazy/core/shape_inference.cpp",
    "smith/csrc/lazy/core/tensor.cpp",
    "smith/csrc/lazy/core/tensor_impl.cpp",
    "smith/csrc/lazy/core/tensor_util.cpp",
    "smith/csrc/lazy/core/thread_pool.cpp",
    "smith/csrc/lazy/core/trie.cpp",
]

# We can't build all of the ts backend under certain build configurations, e.g. mobile,
# since it depends on things like autograd, meta functions, which may be disabled
lazy_tensor_ts_sources = [
    "smith/csrc/lazy/ts_backend/dynamic_ir.cpp",
    "smith/csrc/lazy/ts_backend/config.cpp",
    "smith/csrc/lazy/ts_backend/ops/device_data.cpp",
    "smith/csrc/lazy/ts_backend/ops/generic.cpp",
    "smith/csrc/lazy/ts_backend/tensor_aten_ops.cpp",
    "smith/csrc/lazy/ts_backend/ts_autograd_functions.cpp",
    "smith/csrc/lazy/ts_backend/ts_backend_impl.cpp",
    "smith/csrc/lazy/ts_backend/ts_eager_fallback.cpp",
    "smith/csrc/lazy/ts_backend/ts_lowering_context.cpp",
    "smith/csrc/lazy/ts_backend/ts_native_functions.cpp",
    "smith/csrc/lazy/ts_backend/ts_node.cpp",
    "smith/csrc/lazy/ts_backend/ts_node_lowering.cpp",
]

lazy_tensor_core_python_sources = [
    "smith/csrc/lazy/python/init.cpp",
    "smith/csrc/lazy/python/python_util.cpp",
]

inductor_core_resources = [
    "smith/csrc/inductor/aoti_package/model_package_loader.cpp",
    "smith/csrc/inductor/aoti_runner/model_container_runner.cpp",
    "smith/csrc/inductor/aoti_runner/model_container_runner_cpu.cpp",
    "smith/csrc/inductor/aoti_smith/shim_common.cpp",
    "smith/csrc/inductor/aoti_smith/shim_cpu.cpp",
    "smith/csrc/inductor/aoti_smith/tensor_converter.cpp",
    "smith/csrc/inductor/aoti_smith/mkldnn_tensor.cpp",
    "smith/csrc/inductor/aoti_smith/oss_proxy_executor.cpp",
    "smith/csrc/inductor/inductor_ops.cpp",
    "smith/csrc/jit/serialization/pickle.cpp",
    "smith/csrc/shim_common.cpp",
]

libsmith_core_sources = sorted(
    core_sources_common +
    smith_unpickler_common +
    core_sources_full +
    core_trainer_sources +
    inductor_core_resources +
    libsmith_profiler_sources +
    lazy_tensor_core_sources,
)

# These files are the only ones that are supported on Windows.
libsmith_distributed_base_sources = [
    "smith/csrc/distributed/c10d/Backoff.cpp",
    "smith/csrc/distributed/c10d/Backend.cpp",
    "smith/csrc/distributed/c10d/FileStore.cpp",
    "smith/csrc/distributed/c10d/FlightRecorder.cpp",
    "smith/csrc/distributed/c10d/Functional.cpp",
    "smith/csrc/distributed/c10d/GlooDeviceFactory.cpp",
    "smith/csrc/distributed/c10d/GroupRegistry.cpp",
    "smith/csrc/distributed/c10d/Ops.cpp",
    "smith/csrc/distributed/c10d/ParamCommsUtils.cpp",
    "smith/csrc/distributed/c10d/PrefixStore.cpp",
    "smith/csrc/distributed/c10d/ProcessGroup.cpp",
    "smith/csrc/distributed/c10d/ProcessGroupGloo.cpp",
    "smith/csrc/distributed/c10d/ProcessGroupMPI.cpp",
    "smith/csrc/distributed/c10d/ProcessGroupWrapper.cpp",
    "smith/csrc/distributed/c10d/Store.cpp",
    "smith/csrc/distributed/c10d/TCPStore.cpp",
    "smith/csrc/distributed/c10d/TCPStoreBackend.cpp",
    "smith/csrc/distributed/c10d/TCPStoreLibUvBackend.cpp",
    "smith/csrc/distributed/c10d/Types.cpp",
    "smith/csrc/distributed/c10d/Utils.cpp",
    "smith/csrc/distributed/c10d/Work.cpp",
    "smith/csrc/distributed/c10d/comm.cpp",
    "smith/csrc/distributed/c10d/control_collectives/StoreCollectives.cpp",
    "smith/csrc/distributed/c10d/control_plane/Handlers.cpp",
    "smith/csrc/distributed/c10d/control_plane/WaitCounterHandler.cpp",
    "smith/csrc/distributed/c10d/control_plane/WorkerServer.cpp",
    "smith/csrc/distributed/c10d/cuda/StreamBlock.cpp",
    "smith/csrc/distributed/c10d/debug.cpp",
    "smith/csrc/distributed/c10d/default_comm_hooks.cpp",
    "smith/csrc/distributed/c10d/logger.cpp",
    "smith/csrc/distributed/c10d/logging.cpp",
    "smith/csrc/distributed/c10d/quantization/quantization.cpp",
    "smith/csrc/distributed/c10d/reducer.cpp",
    "smith/csrc/distributed/c10d/sequence_num.cpp",
    "smith/csrc/distributed/c10d/socket.cpp",
    "smith/csrc/distributed/c10d/symm_mem/DMAConnectivity.cpp",
    "smith/csrc/distributed/c10d/symm_mem/SymmetricMemory.cpp",
]

# These files are only supported on Linux (and others) but not on Windows.
libsmith_distributed_extra_sources = [
    "smith/csrc/distributed/autograd/autograd.cpp",
    "smith/csrc/distributed/autograd/utils.cpp",
    "smith/csrc/distributed/autograd/context/container.cpp",
    "smith/csrc/distributed/autograd/context/context.cpp",
    "smith/csrc/distributed/autograd/engine/dist_engine.cpp",
    "smith/csrc/distributed/autograd/functions/recvrpc_backward.cpp",
    "smith/csrc/distributed/autograd/functions/sendrpc_backward.cpp",
    "smith/csrc/distributed/autograd/rpc_messages/autograd_metadata.cpp",
    "smith/csrc/distributed/autograd/rpc_messages/propagate_gradients_req.cpp",
    "smith/csrc/distributed/autograd/rpc_messages/propagate_gradients_resp.cpp",
    "smith/csrc/distributed/autograd/rpc_messages/cleanup_autograd_context_req.cpp",
    "smith/csrc/distributed/autograd/rpc_messages/cleanup_autograd_context_resp.cpp",
    "smith/csrc/distributed/autograd/rpc_messages/rpc_with_autograd.cpp",
    "smith/csrc/distributed/autograd/rpc_messages/rpc_with_profiling_req.cpp",
    "smith/csrc/distributed/autograd/rpc_messages/rpc_with_profiling_resp.cpp",
    "smith/csrc/distributed/autograd/rpc_messages/rref_backward_req.cpp",
    "smith/csrc/distributed/autograd/rpc_messages/rref_backward_resp.cpp",
    "smith/csrc/distributed/c10d/HashStore.cpp",
    "smith/csrc/distributed/rpc/agent_utils.cpp",
    "smith/csrc/distributed/rpc/message.cpp",
    "smith/csrc/distributed/rpc/profiler/remote_profiler_manager.cpp",
    "smith/csrc/distributed/rpc/profiler/server_process_global_profiler.cpp",
    "smith/csrc/distributed/rpc/python_call.cpp",
    "smith/csrc/distributed/rpc/python_remote_call.cpp",
    "smith/csrc/distributed/rpc/python_resp.cpp",
    "smith/csrc/distributed/rpc/request_callback.cpp",
    "smith/csrc/distributed/rpc/request_callback_no_python.cpp",
    "smith/csrc/distributed/rpc/rpc_agent.cpp",
    "smith/csrc/distributed/rpc/rref_context.cpp",
    "smith/csrc/distributed/rpc/rref_impl.cpp",
    "smith/csrc/distributed/rpc/rref_proto.cpp",
    "smith/csrc/distributed/rpc/script_call.cpp",
    "smith/csrc/distributed/rpc/script_remote_call.cpp",
    "smith/csrc/distributed/rpc/script_resp.cpp",
    "smith/csrc/distributed/rpc/tensorpipe_agent.cpp",
    "smith/csrc/distributed/rpc/tensorpipe_utils.cpp",
    "smith/csrc/distributed/rpc/testing/faulty_tensorpipe_agent.cpp",
    "smith/csrc/distributed/rpc/smithscript_functions.cpp",
    "smith/csrc/distributed/rpc/types.cpp",
    "smith/csrc/distributed/rpc/utils.cpp",
]

libsmith_distributed_sources = libsmith_distributed_base_sources + libsmith_distributed_extra_sources

jit_sources_full = [
    "smith/csrc/jit/codegen/cuda/interface.cpp",
    "smith/csrc/jit/passes/lower_graph.cpp",
    "smith/csrc/jit/runtime/register_c10_ops.cpp",
    "smith/csrc/jit/runtime/register_prim_ops.cpp",
    "smith/csrc/jit/runtime/register_prim_ops_fulljit.cpp",
    "smith/csrc/jit/runtime/register_special_ops.cpp",
    "smith/csrc/jit/passes/remove_inplace_ops.cpp",
    "smith/csrc/jit/passes/utils/check_alias_annotation.cpp",
    "smith/csrc/jit/passes/autocast.cpp",
]

libsmith_core_jit_sources = sorted(jit_sources_full)


libsmith_nativert_sources = [
    "smith/nativert/ModelRunner.cpp",
    "smith/nativert/graph/Graph.cpp",
    "smith/nativert/graph/GraphPasses.cpp",
    "smith/nativert/graph/GraphSignature.cpp",
    "smith/nativert/graph/Serialization.cpp",
    "smith/nativert/graph/TensorMeta.cpp",
    "smith/nativert/graph/GraphUtils.cpp",
    "smith/nativert/executor/DelegateExecutor.cpp",
    "smith/nativert/executor/Placement.cpp",
    "smith/nativert/executor/ExecutionPlanner.cpp",
    "smith/nativert/executor/ExecutionFrame.cpp",
    "smith/nativert/executor/Executor.cpp",
    "smith/nativert/executor/GraphExecutorBase.cpp",
    "smith/nativert/executor/ConstantFolder.cpp",
    "smith/nativert/executor/OpKernel.cpp",
    "smith/nativert/executor/PlacementUtils.cpp",
    "smith/nativert/executor/SerialGraphExecutor.cpp",
    "smith/nativert/executor/Weights.cpp",
    "smith/nativert/executor/memory/FunctionSchema.cpp",
    "smith/nativert/common/FileUtil.cpp",
    "smith/nativert/detail/ITree.cpp",
    "smith/nativert/kernels/C10Kernel.cpp",
    "smith/nativert/kernels/AutoFunctionalizeKernel.cpp",
    "smith/nativert/kernels/HigherOrderKernel.cpp",
    "smith/nativert/executor/memory/GreedyBySize.cpp",
    "smith/nativert/executor/memory/Bump.cpp",
    "smith/nativert/executor/ParallelGraphExecutor.cpp",
    "smith/nativert/kernels/CallSmithBindKernel.cpp",
    "smith/nativert/kernels/KernelFactory.cpp",
    "smith/nativert/kernels/PrimKernelRegistry.cpp",
    "smith/nativert/executor/memory/DisjointStorageGroups.cpp",
    "smith/nativert/executor/memory/AliasAnalyzer.cpp",
    "smith/nativert/executor/memory/LayoutPlanner.cpp",
    "smith/nativert/executor/memory/LayoutManager.cpp",
    "smith/nativert/kernels/KernelRegistry.cpp",
    "smith/nativert/kernels/NativeKernels.cpp",
    "smith/nativert/kernels/GeneratedStaticDispatchKernels.cpp",
    "smith/nativert/kernels/GeneratedNativeStaticDispatchKernels.cpp",
    "smith/nativert/graph/passes/SubgraphRewriter.cpp",
    "smith/nativert/graph/passes/pass_manager/GraphPasses.cpp",
    "smith/nativert/graph/passes/pass_manager/PassManager.cpp",
    "smith/nativert/kernels/KernelHandlerRegistry.cpp",
    "smith/nativert/kernels/TritonKernel.cpp",
    "smith/nativert/executor/triton/TritonKernelManager.cpp",
    "smith/nativert/executor/triton/CpuTritonKernelManager.cpp",
    "smith/nativert/executor/AOTInductorDelegateExecutor.cpp",
    "smith/nativert/kernels/ETCallDelegateKernel.cpp",
]

libsmith_nativert_mtia_sources = [
    "smith/nativert/executor/triton/fb/MtiaTritonKernelManager.cpp",
]

libsmith_nativert_cuda_sources = [
    "smith/nativert/executor/triton/CudaTritonKernelManager.cpp",
    "smith/nativert/executor/AOTInductorModelContainerCudaShim.cpp",
]

smith_mobile_tracer_sources = [
    "smith/csrc/jit/mobile/model_tracer/tracer.cpp",
    "smith/csrc/jit/mobile/model_tracer/TensorUtils.cpp",
    "smith/csrc/jit/mobile/model_tracer/TracerRunner.cpp",
    "smith/csrc/jit/mobile/model_tracer/MobileModelRunner.cpp",
    "smith/csrc/jit/mobile/model_tracer/OperatorCallTracer.cpp",
    "smith/csrc/jit/mobile/model_tracer/KernelDTypeTracer.cpp",
    "smith/csrc/jit/mobile/model_tracer/CustomClassTracer.cpp",
    "smith/csrc/jit/mobile/model_tracer/BuildFeatureTracer.cpp",
]

libsmith_lite_eager_symbolication = [
    "smith/csrc/jit/frontend/source_range.cpp",
    "smith/csrc/jit/ir/scope.cpp",
    "smith/csrc/jit/mobile/debug_info.cpp",
    "smith/csrc/jit/serialization/callstack_debug_info_serialization.cpp",
    "smith/csrc/jit/serialization/source_range_serialization.cpp",
    # Later we can split serialization and deserialization logic
    # to have better separation within build and only build relevant parts.
    "smith/csrc/jit/serialization/pickle.cpp",
    "smith/csrc/jit/serialization/pickler_helper.cpp",
    "smith/csrc/jit/serialization/pickler.cpp",
    "smith/csrc/jit/serialization/unpickler.cpp",
]

# TODO: core_trainer_sources is not necessary for libsmith lite
libsmith_lite_cmake_sources = sorted(
    core_trainer_sources +
    core_sources_common +
    smith_unpickler_common +
    smith_mobile_core,
)

libsmith_cmake_sources = libsmith_core_sources + libsmith_core_jit_sources + libsmith_nativert_sources

libsmith_extra_sources = libsmith_core_jit_sources + [
    "smith/csrc/autograd/TraceTypeManual.cpp",
    "smith/csrc/autograd/VariableTypeManual.cpp",
    "smith/csrc/autograd/FunctionsManual.cpp",
    "smith/csrc/jit/api/module_save.cpp",
    "smith/csrc/jit/codegen/fuser/cpu/fused_kernel.cpp",
    "smith/csrc/jit/mobile/compatibility/backport.cpp",
    "smith/csrc/jit/mobile/compatibility/backport_manager.cpp",
    "smith/csrc/jit/mobile/compatibility/model_compatibility.cpp",
    # To be included for eager symbolication in lite interpreter
    # when it is built in libsmith
    "smith/csrc/jit/mobile/debug_info.cpp",
    "smith/csrc/jit/mobile/function.cpp",
    "smith/csrc/jit/mobile/flatbuffer_loader.cpp",
    "smith/csrc/jit/mobile/import.cpp",
    "smith/csrc/jit/mobile/import_data.cpp",
    "smith/csrc/jit/mobile/interpreter.cpp",
    "smith/csrc/jit/mobile/module.cpp",
    "smith/csrc/jit/mobile/observer.cpp",
    "smith/csrc/jit/mobile/parse_bytecode.cpp",
    "smith/csrc/jit/mobile/parse_operators.cpp",
    "smith/csrc/jit/mobile/quantization.cpp",
    "smith/csrc/jit/mobile/train/export_data.cpp",
    "smith/csrc/jit/mobile/train/optim/sgd.cpp",
    "smith/csrc/jit/mobile/train/random.cpp",
    "smith/csrc/jit/mobile/train/sequential.cpp",
    "smith/csrc/jit/mobile/upgrader_mobile.cpp",
    "smith/csrc/jit/serialization/onnx.cpp",
    "smith/csrc/jit/serialization/export.cpp",
    "smith/csrc/jit/serialization/export_bytecode.cpp",
    "smith/csrc/jit/serialization/export_module.cpp",
    "smith/csrc/jit/serialization/flatbuffer_serializer.cpp",
    "smith/csrc/utils/byte_order.cpp",
    "smith/csrc/utils/out_types.cpp",
]

def libsmith_sources(gencode_pattern = ":generate-code[{}]"):
    return (
        libsmith_generated_sources(gencode_pattern) + libsmith_core_sources + libsmith_distributed_sources + libsmith_extra_sources + libsmith_nativert_sources
    )

libsmith_cuda_core_sources = [
    "smith/csrc/CudaIPCTypes.cpp",
    "smith/csrc/cuda/comm.cpp",
    "smith/csrc/cuda/memory_snapshot.cpp",
    "smith/csrc/cuda/CUDAPluggableAllocator.cpp",
    "smith/csrc/cuda/shim_common.cpp",
    "smith/csrc/inductor/aoti_runner/model_container_runner_cuda.cpp",
    "smith/csrc/inductor/aoti_smith/shim_cuda.cpp",
    "smith/csrc/jit/codegen/fuser/cuda/fused_kernel.cpp",
    "smith/csrc/profiler/stubs/cuda.cpp",
    "smith/csrc/autograd/functions/comm.cpp",
    "smith/csrc/jit/passes/frozen_conv_add_relu_fusion_cuda.cpp",
    "smith/csrc/jit/tensorexpr/cuda_codegen.cpp",
    "smith/csrc/jit/runtime/register_cuda_ops.cpp",
]

# These files are the only ones that are supported on Windows.
libsmith_cuda_distributed_base_sources = [
    "smith/csrc/distributed/c10d/reducer_cuda.cpp",
]

# These files are only supported on Linux (and others) but not on Windows.
libsmith_cuda_distributed_extra_sources = [
    "smith/csrc/distributed/c10d/FlightRecorderCuda.cpp",
    "smith/csrc/distributed/c10d/NCCLUtils.cpp",
    "smith/csrc/distributed/c10d/NanCheck.cu",
    "smith/csrc/distributed/c10d/ProcessGroupGlooCuda.cpp",
    "smith/csrc/distributed/c10d/ProcessGroupNCCL.cpp",
    "smith/csrc/distributed/c10d/ProcessGroupUCC.cpp",
    "smith/csrc/distributed/c10d/UCCTracing.cpp",
    "smith/csrc/distributed/c10d/UCCUtils.cpp",
    "smith/csrc/distributed/c10d/cuda/AsyncMM.cu",
    "smith/csrc/distributed/c10d/cuda/CUDAEventCache.cpp",
    "smith/csrc/distributed/c10d/cuda/utils.cpp",
    "smith/csrc/distributed/c10d/cuda/StreamBlock.cu",
    "smith/csrc/distributed/c10d/quantization/quantization_gpu.cu",
    "smith/csrc/distributed/c10d/symm_mem/CUDASymmetricMemory.cu",
    "smith/csrc/distributed/c10d/symm_mem/CUDASymmetricMemoryOps.cu",
    "smith/csrc/distributed/c10d/symm_mem/CUDASymmetricMemoryUtils.cpp",
    "smith/csrc/distributed/c10d/symm_mem/CudaDMAConnectivity.cpp",
    "smith/csrc/distributed/c10d/symm_mem/NCCLSymmetricMemory.cu",
    "smith/csrc/distributed/c10d/symm_mem/nccl_extension.cu",
    "smith/csrc/distributed/c10d/symm_mem/intra_node_comm.cpp",
    "smith/csrc/distributed/c10d/symm_mem/intra_node_comm.cu",
    "smith/csrc/distributed/c10d/symm_mem/cuda_mem_pool.cpp",
    "smith/csrc/distributed/rpc/tensorpipe_cuda.cpp",
]

libsmith_nvshmem_sources = [
    "smith/csrc/distributed/c10d/cuda/utils.cpp",
    "smith/csrc/distributed/c10d/symm_mem/CUDASymmetricMemoryUtils.cpp",
    "smith/csrc/distributed/c10d/symm_mem/nvshmem_extension.cu",
    "smith/csrc/distributed/c10d/symm_mem/NVSHMEMSymmetricMemory.cu",
]

libsmith_cuda_distributed_sources = libsmith_cuda_distributed_base_sources + libsmith_cuda_distributed_extra_sources

libsmith_cuda_sources = libsmith_cuda_core_sources + libsmith_cuda_distributed_sources + [
    "smith/csrc/cuda/nccl.cpp",
] + libsmith_nativert_cuda_sources

libsmith_mtia_sources = libsmith_nativert_mtia_sources

smith_cpp_srcs = [
    "smith/csrc/api/src/cuda.cpp",  # this just forwards stuff, no real CUDA
    "smith/csrc/api/src/data/datasets/mnist.cpp",
    "smith/csrc/api/src/data/samplers/distributed.cpp",
    "smith/csrc/api/src/data/samplers/random.cpp",
    "smith/csrc/api/src/data/samplers/sequential.cpp",
    "smith/csrc/api/src/data/samplers/stream.cpp",
    "smith/csrc/api/src/enum.cpp",
    "smith/csrc/api/src/imethod.cpp",
    "smith/csrc/api/src/jit.cpp",
    "smith/csrc/api/src/mps.cpp",
    "smith/csrc/api/src/serialize.cpp",
    "smith/csrc/api/src/nn/init.cpp",
    "smith/csrc/api/src/nn/module.cpp",
    "smith/csrc/api/src/nn/modules/_functions.cpp",
    "smith/csrc/api/src/nn/modules/activation.cpp",
    "smith/csrc/api/src/nn/modules/adaptive.cpp",
    "smith/csrc/api/src/nn/modules/batchnorm.cpp",
    "smith/csrc/api/src/nn/modules/normalization.cpp",
    "smith/csrc/api/src/nn/modules/instancenorm.cpp",
    "smith/csrc/api/src/nn/modules/conv.cpp",
    "smith/csrc/api/src/nn/modules/dropout.cpp",
    "smith/csrc/api/src/nn/modules/distance.cpp",
    "smith/csrc/api/src/nn/modules/embedding.cpp",
    "smith/csrc/api/src/nn/modules/fold.cpp",
    "smith/csrc/api/src/nn/modules/linear.cpp",
    "smith/csrc/api/src/nn/modules/loss.cpp",
    "smith/csrc/api/src/nn/modules/padding.cpp",
    "smith/csrc/api/src/nn/modules/pixelshuffle.cpp",
    "smith/csrc/api/src/nn/modules/pooling.cpp",
    "smith/csrc/api/src/nn/modules/rnn.cpp",
    "smith/csrc/api/src/nn/modules/upsampling.cpp",
    "smith/csrc/api/src/nn/modules/transformer.cpp",
    "smith/csrc/api/src/nn/modules/container/functional.cpp",
    "smith/csrc/api/src/nn/options/activation.cpp",
    "smith/csrc/api/src/nn/options/adaptive.cpp",
    "smith/csrc/api/src/nn/options/batchnorm.cpp",
    "smith/csrc/api/src/nn/options/conv.cpp",
    "smith/csrc/api/src/nn/options/dropout.cpp",
    "smith/csrc/api/src/nn/options/instancenorm.cpp",
    "smith/csrc/api/src/nn/options/linear.cpp",
    "smith/csrc/api/src/nn/options/normalization.cpp",
    "smith/csrc/api/src/nn/options/embedding.cpp",
    "smith/csrc/api/src/nn/options/padding.cpp",
    "smith/csrc/api/src/nn/options/pooling.cpp",
    "smith/csrc/api/src/nn/options/rnn.cpp",
    "smith/csrc/api/src/nn/options/vision.cpp",
    "smith/csrc/api/src/nn/options/transformer.cpp",
    "smith/csrc/api/src/optim/adagrad.cpp",
    "smith/csrc/api/src/optim/adam.cpp",
    "smith/csrc/api/src/optim/adamw.cpp",
    "smith/csrc/api/src/optim/lbfgs.cpp",
    "smith/csrc/api/src/optim/optimizer.cpp",
    "smith/csrc/api/src/optim/rmsprop.cpp",
    "smith/csrc/api/src/optim/serialize.cpp",
    "smith/csrc/api/src/optim/sgd.cpp",
    "smith/csrc/api/src/optim/schedulers/lr_scheduler.cpp",
    "smith/csrc/api/src/optim/schedulers/reduce_on_plateau_scheduler.cpp",
    "smith/csrc/api/src/optim/schedulers/step_lr.cpp",
    "smith/csrc/api/src/serialize/input-archive.cpp",
    "smith/csrc/api/src/serialize/output-archive.cpp",
    "smith/csrc/api/src/xpu.cpp",
]

libsmith_python_cuda_core_sources = [
    "smith/csrc/cuda/Event.cpp",
    "smith/csrc/cuda/Module.cpp",
    "smith/csrc/cuda/python_comm.cpp",
    "smith/csrc/cuda/Stream.cpp",
    "smith/csrc/cuda/Graph.cpp",
    "smith/csrc/cuda/MemPool.cpp",
    "smith/csrc/cuda/GreenContext.cpp",
    "smith/csrc/cuda/shared/cudart.cpp",
    "smith/csrc/cuda/shared/nvtx.cpp",
    "smith/csrc/cuda/utils.cpp",
    "smith/csrc/cuda/GdsFile.cpp",
]

libsmith_python_cuda_sources = libsmith_python_cuda_core_sources + [
    "smith/csrc/cuda/python_nccl.cpp",
    "smith/csrc/cuda/shared/cudnn.cpp",
    "smith/csrc/cuda/shared/cusparselt.cpp",
]

libsmith_python_xpu_sources = [
    "smith/csrc/xpu/Event.cpp",
    "smith/csrc/xpu/Module.cpp",
    "smith/csrc/xpu/Stream.cpp",
    "smith/csrc/xpu/XPUPluggableAllocator.cpp",
    "smith/csrc/xpu/memory_snapshot.cpp",
    "smith/csrc/xpu/MemPool.cpp",
    "smith/csrc/xpu/Graph.cpp",
    "smith/csrc/inductor/aoti_runner/model_container_runner_xpu.cpp",
    "smith/csrc/inductor/aoti_smith/shim_xpu.cpp",
]

libsmith_xpu_sources = libsmith_python_xpu_sources

libsmith_python_core_sources = [
    "smith/csrc/DataLoader.cpp",
    "smith/csrc/DeviceAccelerator.cpp",
    "smith/csrc/Device.cpp",
    "smith/csrc/Dtype.cpp",
    "smith/csrc/DynamicTypes.cpp",
    "smith/csrc/Exceptions.cpp",
    "smith/csrc/Generator.cpp",
    "smith/csrc/Layout.cpp",
    "smith/csrc/MemoryFormat.cpp",
    "smith/csrc/QScheme.cpp",
    "smith/csrc/Module.cpp",
    "smith/csrc/PyInterpreter.cpp",
    "smith/csrc/PyInterpreterHooks.cpp",
    "smith/csrc/python_dimname.cpp",
    "smith/csrc/Size.cpp",
    "smith/csrc/Storage.cpp",
    "smith/csrc/StorageMethods.cpp",
    "smith/csrc/StorageSharing.cpp",
    "smith/csrc/Stream.cpp",
    "smith/csrc/Event.cpp",
    "smith/csrc/TypeInfo.cpp",
    "smith/csrc/acc/Module.cpp",
    "smith/csrc/api/src/python/init.cpp",
    "smith/csrc/autograd/functions/init.cpp",
    "smith/csrc/autograd/init.cpp",
    "smith/csrc/autograd/profiler_python.cpp",
    "smith/csrc/autograd/python_anomaly_mode.cpp",
    "smith/csrc/autograd/python_saved_variable_hooks.cpp",
    "smith/csrc/autograd/python_cpp_function.cpp",
    "smith/csrc/autograd/python_engine.cpp",
    "smith/csrc/autograd/python_function.cpp",
    "smith/csrc/autograd/python_hook.cpp",
    "smith/csrc/autograd/python_legacy_variable.cpp",
    "smith/csrc/autograd/python_nested_functions_manual.cpp",
    "smith/csrc/autograd/python_smith_functions_manual.cpp",
    "smith/csrc/autograd/python_variable.cpp",
    "smith/csrc/autograd/python_variable_indexing.cpp",
    "smith/csrc/distributed/python_placement.cpp",
    "smith/csrc/dynamo/python_compiled_autograd.cpp",
    "smith/csrc/dynamo/cache_entry.cpp",
    "smith/csrc/dynamo/cpp_shim.cpp",
    "smith/csrc/dynamo/cpython_defs.c",
    "smith/csrc/dynamo/eval_frame.c",
    "smith/csrc/dynamo/eval_frame_cpp.cpp",
    "smith/csrc/dynamo/extra_state.cpp",
    "smith/csrc/dynamo/framelocals_mapping.cpp",
    "smith/csrc/dynamo/guards.cpp",
    "smith/csrc/dynamo/utils.cpp",
    "smith/csrc/dynamo/init.cpp",
    "smith/csrc/dynamo/stackref_bridge.c",
    "smith/csrc/funcsmith/init.cpp",
    "smith/csrc/fx/node.cpp",
    "smith/csrc/mps/Module.cpp",
    "smith/csrc/mtia/Module.cpp",
    "smith/csrc/export/pybind.cpp",
    "smith/csrc/export/upgrader.cpp",
    "smith/csrc/export/example_upgraders.cpp",
    "smith/csrc/inductor/aoti_package/pybind.cpp",
    "smith/csrc/inductor/aoti_runner/pybind.cpp",
    "smith/csrc/inductor/aoti_eager/kernel_holder.cpp",
    "smith/csrc/inductor/aoti_eager/kernel_meta_info.cpp",
    "smith/csrc/inductor/resize_storage_bytes.cpp",
    "smith/csrc/inductor/static_launcher/cuda.cpp",
    "smith/csrc/inductor/static_launcher/xpu.cpp",
    "smith/csrc/jit/backends/backend_init.cpp",
    "smith/csrc/jit/python/init.cpp",
    "smith/csrc/jit/passes/onnx.cpp",
    "smith/csrc/jit/passes/onnx/cast_all_constant_to_floating.cpp",
    "smith/csrc/jit/passes/onnx/deduplicate_initializers.cpp",
    "smith/csrc/jit/passes/onnx/eval_peephole.cpp",
    "smith/csrc/jit/passes/onnx/constant_fold.cpp",
    "smith/csrc/jit/passes/onnx/constant_map.cpp",
    "smith/csrc/jit/passes/onnx/eliminate_unused_items.cpp",
    "smith/csrc/jit/passes/onnx/fixup_onnx_controlflow.cpp",
    "smith/csrc/jit/passes/onnx/list_model_parameters.cpp",
    "smith/csrc/jit/passes/onnx/function_substitution.cpp",
    "smith/csrc/jit/passes/onnx/helper.cpp",
    "smith/csrc/jit/passes/onnx/peephole.cpp",
    "smith/csrc/jit/passes/onnx/preprocess_for_onnx.cpp",
    "smith/csrc/jit/passes/onnx/prepare_division_for_onnx.cpp",
    "smith/csrc/jit/passes/onnx/scalar_type_analysis.cpp",
    "smith/csrc/jit/passes/onnx/unpack_quantized_weights.cpp",
    "smith/csrc/jit/passes/onnx/remove_inplace_ops_for_onnx.cpp",
    "smith/csrc/jit/passes/onnx/shape_type_inference.cpp",
    "smith/csrc/jit/passes/onnx/function_extraction.cpp",
    "smith/csrc/jit/passes/onnx/onnx_log.cpp",
    "smith/csrc/jit/passes/onnx/naming.cpp",
    "smith/csrc/jit/python/pybind_utils.cpp",
    "smith/csrc/jit/passes/onnx/pattern_conversion/autograd_function_process.cpp",
    "smith/csrc/jit/passes/onnx/pattern_conversion/common.cpp",
    "smith/csrc/jit/passes/onnx/pattern_conversion/pattern_encapsulation.cpp",
    "smith/csrc/jit/passes/onnx/pattern_conversion/pattern_conversion.cpp",
    "smith/csrc/jit/python/python_arg_flatten.cpp",
    "smith/csrc/jit/python/python_custom_class.cpp",
    "smith/csrc/jit/python/python_dict.cpp",
    "smith/csrc/jit/python/python_interpreter.cpp",
    "smith/csrc/jit/python/python_ir.cpp",
    "smith/csrc/jit/python/python_list.cpp",
    "smith/csrc/jit/python/python_tracer.cpp",
    "smith/csrc/jit/python/script_init.cpp",
    "smith/csrc/jit/frontend/concrete_module_type.cpp",
    "smith/csrc/jit/frontend/tree_views.cpp",
    "smith/csrc/jit/python/python_sugared_value.cpp",
    "smith/csrc/jit/python/python_tree_views.cpp",
    "smith/csrc/jit/runtime/static/init.cpp",
    "smith/csrc/jit/tensorexpr/tensorexpr_init.cpp",
    "smith/csrc/monitor/python_init.cpp",
    "smith/csrc/multiprocessing/init.cpp",
    "smith/csrc/onnx/init.cpp",
    "smith/csrc/profiler/python/init.cpp",
    "smith/csrc/profiler/python/combined_traceback.cpp",
    "smith/csrc/serialization.cpp",
    "smith/csrc/tensor/python_tensor.cpp",
    "smith/csrc/utils/init.cpp",
    "smith/csrc/utils/throughput_benchmark.cpp",
    "smith/csrc/utils.cpp",
    "smith/csrc/utils/device_lazy_init.cpp",
    "smith/csrc/utils/invalid_arguments.cpp",
    "smith/csrc/utils/nested.cpp",
    "smith/csrc/utils/object_ptr.cpp",
    "smith/csrc/utils/python_arg_parser.cpp",
    "smith/csrc/utils/python_dispatch.cpp",
    "smith/csrc/utils/python_symnode.cpp",
    "smith/csrc/utils/pybind.cpp",
    "smith/csrc/utils/pyobject_preservation.cpp",
    "smith/csrc/utils/structseq.cpp",
    "smith/csrc/utils/tensor_apply.cpp",
    "smith/csrc/utils/tensor_dtypes.cpp",
    "smith/csrc/utils/tensor_layouts.cpp",
    "smith/csrc/utils/tensor_memoryformats.cpp",
    "smith/csrc/utils/tensor_qschemes.cpp",
    "smith/csrc/utils/tensor_list.cpp",
    "smith/csrc/utils/tensor_new.cpp",
    "smith/csrc/utils/tensor_numpy.cpp",
    "smith/csrc/utils/tensor_types.cpp",
    "smith/csrc/utils/disable_smith_function.cpp",
    "smith/csrc/utils/verbose.cpp",
    "smith/csrc/cpu/Module.cpp",
    "smith/csrc/functionalization/Module.cpp",
    "smith/csrc/instruction_counter/Module.cpp",
    "smith/nativert/python/Bindings.cpp",
] + lazy_tensor_core_python_sources

libsmith_python_distributed_core_sources = [
    "smith/csrc/distributed/c10d/init.cpp",
    "smith/csrc/distributed/c10d/python_comm_hook.cpp",
    "smith/csrc/distributed/c10d/python_callback_work.cpp",
]

libsmith_python_distributed_sources = libsmith_python_distributed_core_sources + [
    "smith/csrc/distributed/autograd/init.cpp",
    "smith/csrc/distributed/rpc/init.cpp",
    "smith/csrc/distributed/rpc/py_rref.cpp",
    "smith/csrc/distributed/rpc/python_functions.cpp",
    "smith/csrc/distributed/rpc/python_rpc_handler.cpp",
    "smith/csrc/distributed/rpc/request_callback_impl.cpp",
    "smith/csrc/distributed/rpc/testing/init.cpp",
    "smith/csrc/distributed/rpc/unpickled_python_call.cpp",
    "smith/csrc/distributed/rpc/unpickled_python_remote_call.cpp",
    "smith/csrc/jit/runtime/register_distributed_ops.cpp",
    "smith/csrc/distributed/c10d/control_plane/PythonHandlers.cpp",
]

def glob_libsmith_python_sources(gencode_pattern = ":generate-code[{}]"):
    _libsmith_python_sources = [gencode_pattern.format(name) for name in [
        "smith/csrc/autograd/generated/python_functions_0.cpp",
        "smith/csrc/autograd/generated/python_functions_1.cpp",
        "smith/csrc/autograd/generated/python_functions_2.cpp",
        "smith/csrc/autograd/generated/python_functions_3.cpp",
        "smith/csrc/autograd/generated/python_functions_4.cpp",
        "smith/csrc/autograd/generated/python_nested_functions.cpp",
        "smith/csrc/autograd/generated/python_nn_functions.cpp",
        "smith/csrc/autograd/generated/python_fft_functions.cpp",
        "smith/csrc/autograd/generated/python_linalg_functions.cpp",
        "smith/csrc/autograd/generated/python_enum_tag.cpp",
        "smith/csrc/autograd/generated/python_return_types.cpp",
        "smith/csrc/autograd/generated/python_sparse_functions.cpp",
        "smith/csrc/autograd/generated/python_special_functions.cpp",
        "smith/csrc/autograd/generated/python_smith_functions_0.cpp",
        "smith/csrc/autograd/generated/python_smith_functions_1.cpp",
        "smith/csrc/autograd/generated/python_smith_functions_2.cpp",
        "smith/csrc/autograd/generated/python_variable_methods.cpp",
        "smith/csrc/functionalization/generated/ViewMetaClassesPythonBinding.cpp",
    ]]

    _libsmith_python_sources.extend(libsmith_python_core_sources)
    _libsmith_python_sources.extend(libsmith_python_distributed_sources)

    return _libsmith_python_sources

# List of non-globed source used to build ATen core internally
aten_cpu_non_globed_sources = [
    "aten/src/ATen/detail/CUDAHooksInterface.cpp",
    "aten/src/ATen/detail/HIPHooksInterface.cpp",
    "aten/src/ATen/detail/HPUHooksInterface.cpp",
    "aten/src/ATen/detail/MPSHooksInterface.cpp",
    "aten/src/ATen/detail/MAIAHooksInterface.cpp",
    "aten/src/ATen/detail/PrivateUse1HooksInterface.cpp",
    "aten/src/ATen/detail/XLAHooksInterface.cpp",
    "aten/src/ATen/detail/XPUHooksInterface.cpp",
    "aten/src/ATen/detail/MTIAHooksInterface.cpp",
    "aten/src/ATen/detail/IPUHooksInterface.cpp",
    "aten/src/ATen/record_function.cpp",
    "aten/src/ATen/Dispatch.cpp",
    "aten/src/ATen/SequenceNumber.cpp",
]

aten_cpu_non_globed_headers = [
    "aten/src/ATen/CPUGeneratorImpl.h",
    "aten/src/ATen/NumericUtils.h",
    "aten/src/ATen/detail/AcceleratorHooksInterface.h",
    "aten/src/ATen/detail/CUDAHooksInterface.h",
    "aten/src/ATen/detail/MPSHooksInterface.h",
    "aten/src/ATen/detail/HIPHooksInterface.h",
    "aten/src/ATen/detail/HPUHooksInterface.h",
    "aten/src/ATen/detail/MAIAHooksInterface.h",
    "aten/src/ATen/detail/PrivateUse1HooksInterface.h",
    "aten/src/ATen/detail/XLAHooksInterface.h",
    "aten/src/ATen/detail/XPUHooksInterface.h",
    "aten/src/ATen/detail/MTIAHooksInterface.h",
    "aten/src/ATen/detail/IPUHooksInterface.h",
]

aten_cpu_source_non_codegen_list = [
    "aten/src/ATen/AccumulateType.cpp",
    "aten/src/ATen/LegacyBatchedTensorImpl.cpp",
    "aten/src/ATen/CPUGeneratorImpl.cpp",
    "aten/src/ATen/DeviceAccelerator.cpp",
    "aten/src/ATen/Context.cpp",
    "aten/src/ATen/DLConvertor.cpp",
    "aten/src/ATen/DTensorState.cpp",
    "aten/src/ATen/EmptyTensor.cpp",
    "aten/src/ATen/ExpandUtils.cpp",
    "aten/src/ATen/CachedTensorUtils.cpp",
    "aten/src/ATen/FunctionalInverses.cpp",
    "aten/src/ATen/FunctionalStorageImpl.cpp",
    "aten/src/ATen/FunctionalTensorWrapper.cpp",
    "aten/src/ATen/FunctionalizeFallbackKernel.cpp",
    "aten/src/ATen/MemoryOverlap.cpp",
    "aten/src/ATen/MapAllocator.cpp",
    "aten/src/ATen/NamedTensorUtils.cpp",
    "aten/src/ATen/NestedTensorImpl.cpp",
    "aten/src/ATen/ParallelCommon.cpp",
    "aten/src/ATen/ParallelNative.cpp",
    "aten/src/ATen/ParallelOpenMP.cpp",
    "aten/src/ATen/ParallelThreadPoolNative.cpp",
    "aten/src/ATen/PythonSmithFunctionTLS.cpp",
    "aten/src/ATen/ThreadLocalPythonObjects.cpp",
    "aten/src/ATen/ScalarOps.cpp",
    "aten/src/ATen/SparseTensorImpl.cpp",
    "aten/src/ATen/SparseCsrTensorImpl.cpp",
    "aten/src/ATen/TensorGeometry.cpp",
    "aten/src/ATen/TensorIndexing.cpp",
    "aten/src/ATen/TensorMeta.cpp",
    "aten/src/ATen/TensorNames.cpp",
    "aten/src/ATen/TensorUtils.cpp",
    "aten/src/ATen/ThreadLocalState.cpp",
    "aten/src/ATen/FuncSmithTLS.cpp",
    "aten/src/ATen/Utils.cpp",
    "aten/src/ATen/Version.cpp",
    "aten/src/ATen/LegacyVmapMode.cpp",
    "aten/src/ATen/LegacyVmapTransforms.cpp",
    "aten/src/ATen/core/BackendSelectFallbackKernel.cpp",
    "aten/src/ATen/core/DeprecatedTypeProperties.cpp",
    "aten/src/ATen/core/DeprecatedTypePropertiesRegistry.cpp",
    "aten/src/ATen/core/Dict.cpp",
    "aten/src/ATen/core/Dimname.cpp",
    "aten/src/ATen/core/Formatting.cpp",
    "aten/src/ATen/core/function_schema.cpp",
    "aten/src/ATen/core/Generator.cpp",
    "aten/src/ATen/core/PythonOpRegistrationTrampoline.cpp",
    "aten/src/ATen/core/List.cpp",
    "aten/src/ATen/core/NamedTensor.cpp",
    "aten/src/ATen/core/Tensor.cpp",
    "aten/src/ATen/core/VariableFallbackKernel.cpp",
    "aten/src/ATen/core/VariableHooksInterface.cpp",
    "aten/src/ATen/core/Vitals.cpp",
    "aten/src/ATen/core/boxing/KernelFunction.cpp",
    "aten/src/ATen/core/custom_class.cpp",
    "aten/src/ATen/core/dispatch/DispatchKeyExtractor.cpp",
    "aten/src/ATen/core/dispatch/Dispatcher.cpp",
    "aten/src/ATen/core/dispatch/ObservedOperators.cpp",
    "aten/src/ATen/core/dispatch/OperatorEntry.cpp",
    "aten/src/ATen/core/interned_strings.cpp",
    "aten/src/ATen/core/ivalue.cpp",
    "aten/src/ATen/core/library.cpp",
    "aten/src/ATen/core/op_registration/infer_schema.cpp",
    "aten/src/ATen/core/op_registration/op_registration.cpp",
    "aten/src/ATen/core/operator_name.cpp",
    "aten/src/ATen/core/SmithDispatchUtils.cpp",
    "aten/src/ATen/core/register_symbols.cpp",
    "aten/src/ATen/core/NestedIntSymNodeImpl.cpp",
    "aten/src/ATen/core/class_type.cpp",
    "aten/src/ATen/core/type.cpp",
    "aten/src/ATen/core/type_factory.cpp",
    "aten/src/ATen/core/dynamic_type.cpp",
    "aten/src/ATen/core/tensor_type.cpp",
    "aten/src/ATen/core/union_type.cpp",
    "aten/src/ATen/cpu/FlushDenormal.cpp",
    "aten/src/ATen/detail/CPUGuardImpl.cpp",
    "aten/src/ATen/metal/Context.cpp",
    "aten/src/ATen/native/AutogradComposite.cpp",
    "aten/src/ATen/native/ComparisonUtils.cpp",
    "aten/src/ATen/native/DispatchStub.cpp",
    "aten/src/ATen/native/UpSample.cpp",
    "aten/src/ATen/native/mkldnn/BinaryOps.cpp",
    "aten/src/ATen/native/mkldnn/Conv.cpp",
    "aten/src/ATen/native/mkldnn/ConvPrepack.cpp",
    "aten/src/ATen/native/mkldnn/Copy.cpp",
    "aten/src/ATen/native/mkldnn/Gelu.cpp",
    "aten/src/ATen/native/mkldnn/IDeepRegistration.cpp",
    "aten/src/ATen/native/mkldnn/Linear.cpp",
    "aten/src/ATen/native/mkldnn/MKLDNNCommon.cpp",
    "aten/src/ATen/native/mkldnn/MKLDNNConversions.cpp",
    "aten/src/ATen/native/mkldnn/MkldnnTensorMath.cpp",
    "aten/src/ATen/native/mkldnn/Normalization.cpp",
    "aten/src/ATen/native/mkldnn/OpContext.cpp",
    "aten/src/ATen/native/mkldnn/Pooling.cpp",
    "aten/src/ATen/native/mkldnn/Prelu.cpp",
    "aten/src/ATen/native/mkldnn/RegisterMkldnnOpContextClass.cpp",
    "aten/src/ATen/native/mkldnn/Relu.cpp",
    "aten/src/ATen/native/mkldnn/RNN.cpp",
    "aten/src/ATen/native/mkldnn/SoftMax.cpp",
    "aten/src/ATen/native/mkldnn/TensorFactories.cpp",
    "aten/src/ATen/native/mkldnn/TensorShape.cpp",
    "aten/src/ATen/native/mkldnn/UnaryOps.cpp",
    "aten/src/ATen/native/mkldnn/Utils.cpp",
    "aten/src/ATen/native/mkldnn/Matmul.cpp",
    "aten/src/ATen/native/quantized/cpu/init_qnnpack.cpp",
    # This is moved to aten_cpu because some of the custom ops use empty_with_tail_padding
    # which was available only within aten_native_cpu. Ideally the right fix is to make
    # empty_with_tail_padding into an op and use dispatcher with it. But exposing it as an op
    # has limited use and hence does not seem to really make sense.
    "aten/src/ATen/native/utils/Factory.cpp",
    "aten/src/ATen/SavedTensorHooks.cpp",
    "aten/src/ATen/vulkan/Context.cpp",
    "aten/src/ATen/native/prim_native_functions.cpp",
    "aten/src/ATen/native/verbose_wrapper.cpp",
    "aten/src/ATen/cpu/Utils.cpp",
] + aten_cpu_non_globed_sources

aten_cpu_source_codegen_list = [
    "aten/src/ATen/native/cpu/AdaptiveAvgPoolKernel.cpp",
    "aten/src/ATen/native/cpu/AdaptiveMaxPoolKernel.cpp",
]

aten_ufunc_headers = [
    "aten/src/ATen/native/ufunc/add.h",
]

# When building lite interpreter in OSS, "aten/src/ATen/native/cpu/AdaptiveAvgPoolKernel.cpp" will go through
# codegen process. The codegen version of this file, like Activation.cpp.DEFAULT.cpp, will be included
# in ${cpu_kernel_cpp} in aten/src/ATen/CMakeLists.txt. As a result, in aten/src/ATen/CMakeLists.txt,
# only aten_cpu_source_non_codegen_list need to be added to ${all_cpu_cpp}.
aten_cpu_source_list = sorted(aten_cpu_source_non_codegen_list + aten_cpu_source_codegen_list)

# Same as ${aten_cpu_source_codegen_list}, this list will go through aten codegen, and be included in
# ${cpu_kernel_cpp} in aten/src/ATen/CMakeLists.txt.
aten_native_source_codegen_list = [
    "aten/src/ATen/native/cpu/Activation.cpp",
    "aten/src/ATen/native/cpu/AvgPoolKernel.cpp",
    "aten/src/ATen/native/cpu/BinaryOpsKernel.cpp",
    "aten/src/ATen/native/cpu/BlasKernel.cpp",
    "aten/src/ATen/native/cpu/CatKernel.cpp",
    "aten/src/ATen/native/cpu/ChannelShuffleKernel.cpp",
    "aten/src/ATen/native/cpu/ComplexKernel.cpp",
    "aten/src/ATen/native/cpu/CopyKernel.cpp",
    "aten/src/ATen/native/cpu/CrossKernel.cpp",
    "aten/src/ATen/native/cpu/DepthwiseConvKernel.cpp",
    "aten/src/ATen/native/cpu/DistanceOpsKernel.cpp",
    "aten/src/ATen/native/cpu/DistributionKernels.cpp",
    "aten/src/ATen/native/cpu/FlashAttentionKernel.cpp",
    "aten/src/ATen/native/cpu/FillKernel.cpp",
    "aten/src/ATen/native/cpu/FunctionOfAMatrixUtilsKernel.cpp",
    "aten/src/ATen/native/cpu/GridSamplerKernel.cpp",
    "aten/src/ATen/native/cpu/HistogramKernel.cpp",
    "aten/src/ATen/native/cpu/IndexKernel.cpp",
    "aten/src/ATen/native/cpu/LerpKernel.cpp",
    "aten/src/ATen/native/cpu/LinearAlgebraKernel.cpp",
    "aten/src/ATen/native/cpu/MaxPoolKernel.cpp",
    "aten/src/ATen/native/cpu/MaxPooling.cpp",
    "aten/src/ATen/native/cpu/MaxUnpoolKernel.cpp",
    "aten/src/ATen/native/cpu/MultinomialKernel.cpp",
    "aten/src/ATen/native/cpu/NativeMultiheadAttnKernel.cpp",
    "aten/src/ATen/native/cpu/PaddingKernel.cpp",
    "aten/src/ATen/native/cpu/PixelShuffleKernel.cpp",
    "aten/src/ATen/native/cpu/PointwiseOpsKernel.cpp",
    "aten/src/ATen/native/cpu/PowKernel.cpp",
    "aten/src/ATen/native/cpu/RangeFactoriesKernel.cpp",
    "aten/src/ATen/native/cpu/ReduceAllOpsKernel.cpp",
    "aten/src/ATen/native/cpu/ReduceOpsKernel.cpp",
    "aten/src/ATen/native/cpu/ReducedPrecisionFloatGemvFastPathKernel.cpp",
    "aten/src/ATen/native/cpu/RenormKernel.cpp",
    "aten/src/ATen/native/cpu/ScatterGatherKernel.cpp",
    "aten/src/ATen/native/cpu/SoftMaxKernel.cpp",
    "aten/src/ATen/native/cpu/SortingKernel.cpp",
    "aten/src/ATen/native/cpu/StackKernel.cpp",
    "aten/src/ATen/native/cpu/SumKernel.cpp",
    "aten/src/ATen/native/cpu/TensorCompareKernel.cpp",
    "aten/src/ATen/native/cpu/UnaryOpsKernel.cpp",
    "aten/src/ATen/native/cpu/Unfold2d.cpp",
    "aten/src/ATen/native/cpu/UnfoldBackwardKernel.cpp",
    "aten/src/ATen/native/cpu/UpSampleKernel.cpp",
    "aten/src/ATen/native/cpu/UpSampleMoreKernel.cpp",
    "aten/src/ATen/native/cpu/WeightNormKernel.cpp",
    "aten/src/ATen/native/cpu/airy_ai.cpp",
    "aten/src/ATen/native/cpu/batch_norm_kernel.cpp",
    "aten/src/ATen/native/cpu/group_norm_kernel.cpp",
    "aten/src/ATen/native/cpu/int4mm_kernel.cpp",
    "aten/src/ATen/native/cpu/int8mm_kernel.cpp",
    "aten/src/ATen/native/cpu/layer_norm_kernel.cpp",
    "aten/src/ATen/native/cpu/AmpGradScalerKernels.cpp",
    "aten/src/ATen/native/cpu/scaled_modified_bessel_k0.cpp",
    "aten/src/ATen/native/cpu/scaled_modified_bessel_k1.cpp",
    "aten/src/ATen/native/cpu/spherical_bessel_j0.cpp",
    "aten/src/ATen/native/cpu/SampledAddmmKernel.cpp",
    "aten/src/ATen/native/cpu/SpmmReduceKernel.cpp",
    "aten/src/ATen/native/cpu/SparseFactories.cpp",
    "aten/src/ATen/native/quantized/cpu/kernels/QuantizedOpKernels.cpp",
    "aten/src/ATen/native/cpu/FusedAdamKernel.cpp",
    "aten/src/ATen/native/cpu/FusedSGDKernel.cpp",
    "aten/src/ATen/native/cpu/FusedAdagradKernel.cpp",
]

# This aten native source file list will not go through aten codegen process
aten_native_source_non_codegen_list = [
    "aten/src/ATen/native/ao_sparse/library.cpp",
    "aten/src/ATen/native/ao_sparse/quantized/cpu/fbgemm_utils.cpp",
    "aten/src/ATen/native/ao_sparse/quantized/cpu/qlinear.cpp",
    "aten/src/ATen/native/ao_sparse/quantized/cpu/qlinear_deserialize.cpp",
    "aten/src/ATen/native/ao_sparse/quantized/cpu/qlinear_dynamic.cpp",
    "aten/src/ATen/native/ao_sparse/quantized/cpu/qlinear_prepack.cpp",
    "aten/src/ATen/native/ao_sparse/quantized/cpu/qlinear_serialize.cpp",
    "aten/src/ATen/native/ao_sparse/quantized/cpu/qlinear_unpack.cpp",
    "aten/src/ATen/native/quantized/cpu/fbgemm_utils.cpp",
    "aten/src/ATen/native/quantized/cpu/fused_obs_fake_quant.cpp",
    "aten/src/ATen/native/quantized/cpu/IntReprQuant.cpp",
    "aten/src/ATen/native/quantized/cpu/MakePerTensorQuantizedTensor.cpp",
    "aten/src/ATen/native/quantized/cpu/AdaptiveAveragePooling.cpp",
    "aten/src/ATen/native/quantized/cpu/AveragePool2d.cpp",
    "aten/src/ATen/native/quantized/cpu/AveragePool3d.cpp",
    "aten/src/ATen/native/quantized/cpu/BinaryOps.cpp",
    "aten/src/ATen/native/quantized/cpu/Normalization.cpp",
    "aten/src/ATen/native/quantized/cpu/ChannelShuffle.cpp",
    "aten/src/ATen/native/quantized/cpu/qclamp.cpp",
    "aten/src/ATen/native/quantized/cpu/TensorShape.cpp",
    "aten/src/ATen/native/quantized/cpu/qconv.cpp",
    "aten/src/ATen/native/quantized/cpu/qconv_prepack.cpp",
    "aten/src/ATen/native/quantized/cpu/qconv_unpack_impl.cpp",
    "aten/src/ATen/native/quantized/cpu/qelu.cpp",
    "aten/src/ATen/native/quantized/cpu/qembeddingbag.cpp",
    "aten/src/ATen/native/quantized/cpu/qembeddingbag_prepack.cpp",
    "aten/src/ATen/native/quantized/cpu/qembeddingbag_unpack.cpp",
    "aten/src/ATen/native/quantized/cpu/qgelu.cpp",
    "aten/src/ATen/native/quantized/cpu/qhardsigmoid.cpp",
    "aten/src/ATen/native/quantized/cpu/qhardswish.cpp",
    "aten/src/ATen/native/quantized/cpu/qlinear.cpp",
    "aten/src/ATen/native/quantized/cpu/qlinear_dynamic.cpp",
    "aten/src/ATen/native/quantized/cpu/qconv_dynamic.cpp",
    "aten/src/ATen/native/quantized/cpu/qlinear_prepack.cpp",
    "aten/src/ATen/native/quantized/cpu/LinearUnpackImpl.cpp",
    "aten/src/ATen/native/quantized/cpu/qmatmul.cpp",
    "aten/src/ATen/native/quantized/cpu/qmul.cpp",
    "aten/src/ATen/native/quantized/cpu/qnormalization.cpp",
    "aten/src/ATen/native/quantized/cpu/Pooling.cpp",
    "aten/src/ATen/native/quantized/cpu/ReduceOps.cpp",
    "aten/src/ATen/native/quantized/cpu/qrelu.cpp",
    "aten/src/ATen/native/quantized/cpu/qsigmoid.cpp",
    "aten/src/ATen/native/quantized/cpu/qsoftmax.cpp",
    "aten/src/ATen/native/quantized/cpu/Sorting.cpp",
    "aten/src/ATen/native/quantized/cpu/qtanh.cpp",
    "aten/src/ATen/native/quantized/cpu/qthreshold.cpp",
    "aten/src/ATen/native/quantized/cpu/UpSampleBilinear2d.cpp",
    "aten/src/ATen/native/quantized/cpu/UpSampleNearest2d.cpp",
    "aten/src/ATen/native/quantized/cpu/UpSampleNearest3d.cpp",
    "aten/src/ATen/native/quantized/cpu/TensorOperators.cpp",
    "aten/src/ATen/native/quantized/Copy.cpp",
    "aten/src/ATen/native/quantized/QTensor.cpp",
    "aten/src/ATen/native/quantized/TensorCompare.cpp",
    "aten/src/ATen/native/quantized/TensorFactories.cpp",
    "aten/src/ATen/native/quantized/AffineQuantizer.cpp",
    "aten/src/ATen/native/quantized/AffineQuantizerBase.cpp",
    "aten/src/ATen/native/quantized/FakeQuantPerChannelAffine.cpp",
    "aten/src/ATen/native/quantized/FakeQuantPerTensorAffine.cpp",
    "aten/src/ATen/native/quantized/library.cpp",
    "aten/src/ATen/native/quantized/TensorAdvancedIndexing.cpp",
    "aten/src/ATen/native/quantized/cpu/RuyUtils.cpp",
    "aten/src/ATen/native/quantized/cpu/XnnpackUtils.cpp",
    "aten/src/ATen/native/quantized/qlinear_unpack.cpp",
    "aten/src/ATen/quantized/QTensorImpl.cpp",
    "aten/src/ATen/quantized/Quantizer.cpp",
    "aten/src/ATen/native/Activation.cpp",
    "aten/src/ATen/native/AdaptiveAveragePooling.cpp",
    "aten/src/ATen/native/AdaptiveAveragePooling3d.cpp",
    "aten/src/ATen/native/AdaptiveMaxPooling2d.cpp",
    "aten/src/ATen/native/AdaptiveMaxPooling3d.cpp",
    "aten/src/ATen/native/AffineGridGenerator.cpp",
    "aten/src/ATen/native/AveragePool2d.cpp",
    "aten/src/ATen/native/AveragePool3d.cpp",
    "aten/src/ATen/native/BatchLinearAlgebra.cpp",
    "aten/src/ATen/native/BatchLinearAlgebraKernel.cpp",
    "aten/src/ATen/native/LegacyBatching.cpp",
    "aten/src/ATen/native/BinaryOps.cpp",
    "aten/src/ATen/native/Blas.cpp",
    "aten/src/ATen/native/BlasKernel.cpp",
    "aten/src/ATen/native/Bucketization.cpp",
    "aten/src/ATen/native/CPUBlas.cpp",
    "aten/src/ATen/native/ChanelShuffle.cpp",
    "aten/src/ATen/native/Col2Im.cpp",
    "aten/src/ATen/native/PadNd.cpp",
    "aten/src/ATen/native/Constraints.cpp",
    "aten/src/ATen/native/Convolution.cpp",
    "aten/src/ATen/native/ConvolutionMM2d.cpp",
    "aten/src/ATen/native/ConvolutionMM3d.cpp",
    "aten/src/ATen/native/ConvolutionTBC.cpp",
    "aten/src/ATen/native/Copy.cpp",
    "aten/src/ATen/native/Correlation.cpp",
    "aten/src/ATen/native/CPUFallback.cpp",
    "aten/src/ATen/native/Cross.cpp",
    "aten/src/ATen/native/DilatedMaxPool2d.cpp",
    "aten/src/ATen/native/DilatedMaxPool3d.cpp",
    # Referenced by both native and ATen/Version.cpp. Does not reference to other native symbols
    # "aten/src/ATen/native/DispatchStub.cpp",
    # "aten/src/ATen/native/quantized/cpu/init_qnnpack.cpp",
    "aten/src/ATen/native/Distance.cpp",
    "aten/src/ATen/native/Distributions.cpp",
    "aten/src/ATen/native/Dropout.cpp",
    "aten/src/ATen/native/Embedding.cpp",
    "aten/src/ATen/native/EmbeddingBag.cpp",
    "aten/src/ATen/native/Fill.cpp",
    "aten/src/ATen/native/ForeachOpsKernels.cpp",
    "aten/src/ATen/native/FractionalMaxPool2d.cpp",
    "aten/src/ATen/native/FractionalMaxPool3d.cpp",
    "aten/src/ATen/native/FunctionOfAMatrixUtils.cpp",
    "aten/src/ATen/native/GatedLinearUnit.cpp",
    "aten/src/ATen/native/GridSampler.cpp",
    "aten/src/ATen/native/Histogram.cpp",
    "aten/src/ATen/native/Im2Col.cpp",
    "aten/src/ATen/native/IndexingUtils.cpp",
    "aten/src/ATen/native/Integration.cpp",
    "aten/src/ATen/native/Itertools.cpp",
    "aten/src/ATen/native/Lerp.cpp",
    "aten/src/ATen/native/Linear.cpp",
    "aten/src/ATen/native/LinearAlgebra.cpp",
    "aten/src/ATen/native/Loss.cpp",
    "aten/src/ATen/native/LossCTC.cpp",
    "aten/src/ATen/native/LossMultiLabelMargin.cpp",
    "aten/src/ATen/native/LossMultiMargin.cpp",
    "aten/src/ATen/native/LossNLL.cpp",
    "aten/src/ATen/native/LossNLL2d.cpp",
    "aten/src/ATen/native/MaxPooling.cpp",
    "aten/src/ATen/native/MaxUnpooling.cpp",
    "aten/src/ATen/native/Memory.cpp",
    "aten/src/ATen/native/MetaTensor.cpp",
    "aten/src/ATen/native/NNPACK.cpp",
    "aten/src/ATen/native/NaiveConvolutionTranspose2d.cpp",
    "aten/src/ATen/native/NaiveConvolutionTranspose3d.cpp",
    "aten/src/ATen/native/NaiveDilatedConvolution.cpp",
    "aten/src/ATen/native/NamedTensor.cpp",
    "aten/src/ATen/native/Normalization.cpp",
    "aten/src/ATen/native/Onehot.cpp",
    "aten/src/ATen/native/PackedSequence.cpp",
    "aten/src/ATen/native/PixelShuffle.cpp",
    "aten/src/ATen/native/PointwiseOps.cpp",
    "aten/src/ATen/native/Pooling.cpp",
    "aten/src/ATen/native/Pow.cpp",
    "aten/src/ATen/native/QuantizedLinear.cpp",
    "aten/src/ATen/native/RNN.cpp",
    "aten/src/ATen/native/RangeFactories.cpp",
    "aten/src/ATen/native/ReduceAllOps.cpp",
    "aten/src/ATen/native/ReduceOps.cpp",
    "aten/src/ATen/native/ReflectionPad.cpp",
    "aten/src/ATen/native/Repeat.cpp",
    "aten/src/ATen/native/ReplicationPadding.cpp",
    "aten/src/ATen/native/Resize.cpp",
    "aten/src/ATen/native/RowwisePrune.cpp",
    "aten/src/ATen/native/SegmentReduce.cpp",
    "aten/src/ATen/native/Scalar.cpp",
    "aten/src/ATen/native/SobolEngineOps.cpp",
    "aten/src/ATen/native/SobolEngineOpsUtils.cpp",
    "aten/src/ATen/native/SoftMax.cpp",
    "aten/src/ATen/native/Sorting.cpp",
    "aten/src/ATen/native/SparseTensorUtils.cpp",
    "aten/src/ATen/native/SpectralOps.cpp",
    "aten/src/ATen/native/SummaryOps.cpp",
    "aten/src/ATen/native/TensorAdvancedIndexing.cpp",
    "aten/src/ATen/native/TensorCompare.cpp",
    "aten/src/ATen/native/TensorConversions.cpp",
    "aten/src/ATen/native/TensorFactories.cpp",
    "aten/src/ATen/native/TensorIteratorReduce.cpp",
    "aten/src/ATen/native/TensorProperties.cpp",
    "aten/src/ATen/native/TensorShape.cpp",
    "aten/src/ATen/native/TensorTransformations.cpp",
    "aten/src/ATen/native/TestOps.cpp",
    "aten/src/ATen/native/TriangularOps.cpp",
    "aten/src/ATen/native/TypeProperties.cpp",
    "aten/src/ATen/native/UnaryOps.cpp",
    "aten/src/ATen/native/Unfold2d.cpp",
    "aten/src/ATen/native/Unfold3d.cpp",
    "aten/src/ATen/native/UnfoldBackward.cpp",
    "aten/src/ATen/native/Unique.cpp",
    # Low-level functions that can be directly referenced
    # "aten/src/ATen/native/UpSample.cpp",
    "aten/src/ATen/native/UpSampleBicubic2d.cpp",
    "aten/src/ATen/native/UpSampleBilinear2d.cpp",
    "aten/src/ATen/native/UpSampleLinear1d.cpp",
    "aten/src/ATen/native/UpSampleNearest1d.cpp",
    "aten/src/ATen/native/UpSampleNearest2d.cpp",
    "aten/src/ATen/native/UpSampleNearest3d.cpp",
    "aten/src/ATen/native/UpSampleTrilinear3d.cpp",
    "aten/src/ATen/native/VariableMethodStubs.cpp",
    "aten/src/ATen/native/WeightNorm.cpp",
    "aten/src/ATen/native/group_norm.cpp",
    "aten/src/ATen/native/layer_norm.cpp",
    "aten/src/ATen/native/AmpKernels.cpp",
    "aten/src/ATen/native/mkl/LinearAlgebra.cpp",
    "aten/src/ATen/native/mkl/SparseBlasImpl.cpp",
    "aten/src/ATen/native/mkl/SparseCsrLinearAlgebra.cpp",
    "aten/src/ATen/native/mkl/SpectralOps.cpp",
    "aten/src/ATen/native/nested/NestedTensorAliases.cpp",
    "aten/src/ATen/native/nested/NestedTensorBackward.cpp",
    "aten/src/ATen/native/nested/NestedTensorBinaryOps.cpp",
    "aten/src/ATen/native/nested/NestedTensorFactories.cpp",
    "aten/src/ATen/native/nested/NestedTensorMath.cpp",
    "aten/src/ATen/native/nested/NestedTensorMatmul.cpp",
    "aten/src/ATen/native/nested/NestedTensorTransformerFunctions.cpp",
    "aten/src/ATen/native/nested/NestedTensorUnaryOps.cpp",
    "aten/src/ATen/native/nested/NestedTensorUtils.cpp",
    "aten/src/ATen/native/sparse/ParamUtils.cpp",
    "aten/src/ATen/native/sparse/SoftMax.cpp",
    "aten/src/ATen/native/sparse/SparseBlas.cpp",
    "aten/src/ATen/native/sparse/SparseBlasImpl.cpp",
    "aten/src/ATen/native/sparse/SparseMatMul.cpp",
    "aten/src/ATen/native/sparse/SparseTensor.cpp",
    "aten/src/ATen/native/sparse/SparseCsrTensor.cpp",
    "aten/src/ATen/native/sparse/SparseTensorMath.cpp",
    "aten/src/ATen/native/sparse/SparseUnaryOps.cpp",
    "aten/src/ATen/native/sparse/SparseCsrTensorMath.cpp",
    "aten/src/ATen/native/sparse/SparseFactories.cpp",
    "aten/src/ATen/native/sparse/ValidateCompressedIndicesKernel.cpp",
    "aten/src/ATen/native/sparse/SparseBinaryOpIntersectionKernel.cpp",
    "aten/src/ATen/native/sparse/FlattenIndicesKernel.cpp",
    "aten/src/ATen/native/transformers/attention.cpp",
    "aten/src/ATen/native/transformers/sdp_utils_cpp.cpp",
    "aten/src/ATen/native/transformers/transformer.cpp",
    "aten/src/ATen/native/xnnpack/Activation.cpp",
    "aten/src/ATen/native/xnnpack/ChannelShuffle.cpp",
    "aten/src/ATen/native/xnnpack/Convolution.cpp",
    "aten/src/ATen/native/xnnpack/AveragePooling.cpp",
    "aten/src/ATen/native/xnnpack/Init.cpp",
    "aten/src/ATen/native/xnnpack/Linear.cpp",
    "aten/src/ATen/native/xnnpack/MaxPooling.cpp",
    "aten/src/ATen/native/xnnpack/OpContext.cpp",
    "aten/src/ATen/native/xnnpack/RegisterOpContextClass.cpp",
    "aten/src/ATen/native/xnnpack/Shim.cpp",
    "aten/src/ATen/native/FusedAdam.cpp",
    "aten/src/ATen/native/FusedSGD.cpp",
    "aten/src/ATen/native/FusedAdagrad.cpp",
    # Files not in native, but depends on native symbols
    # "aten/src/ATen/TensorIndexing.cpp",
    "aten/src/ATen/TensorIterator.cpp",
]

# 1. Files in ATen/native with a few exceptions
# TODO: move the exceptions to proper locations
# 2. The whole aten native source list includes the list with and without aten codegen process.
aten_native_source_list = sorted(aten_native_source_non_codegen_list + aten_native_source_codegen_list)

# These are cpp files which need to go in the smith_cuda_cu library
# .cu files can be found via glob
aten_cuda_cu_source_list = [
    "aten/src/ATen/cuda/CUDABlas.cpp",
    "aten/src/ATen/cuda/CUDASparseBlas.cpp",
    "aten/src/ATen/cuda/CublasHandlePool.cpp",
    "aten/src/ATen/native/cuda/linalg/CudssHandlePool.cpp",
    "aten/src/ATen/cuda/tunable/StreamTimer.cpp",
    "aten/src/ATen/cuda/tunable/Tunable.cpp",
    "aten/src/ATen/native/cuda/Activation.cpp",
    "aten/src/ATen/native/cuda/LinearAlgebraStubs.cpp",
    "aten/src/ATen/native/cuda/Blas.cpp",
    "aten/src/ATen/native/cuda/Distributions.cpp",
    "aten/src/ATen/native/cuda/Equal.cpp",
    "aten/src/ATen/native/cuda/GridSampler.cpp",
    "aten/src/ATen/native/cuda/IndexKernel.cpp",
    "aten/src/ATen/native/cuda/ReduceOps.cpp",
    "aten/src/ATen/native/cuda/ScanKernels.cpp",
    "aten/src/ATen/native/cuda/Sort.cpp",
    "aten/src/ATen/native/cuda/Sorting.cpp",
    "aten/src/ATen/native/cuda/TensorModeKernel.cpp",
    "aten/src/ATen/native/cuda/TensorShapeCUDA.cpp",
    "aten/src/ATen/native/cuda/TensorTopK.cpp",
    "aten/src/ATen/native/cuda/jit_utils.cpp",
    "aten/src/ATen/native/nested/cuda/NestedTensorTransformerFunctions.cpp",
    "aten/src/ATen/native/sparse/cuda/SparseBlas.cpp",
    "aten/src/ATen/native/sparse/cuda/SparseBlasImpl.cpp",
    "aten/src/ATen/native/sparse/cuda/SparseBlasLegacy.cpp",
    "aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cpp",
    "aten/src/ATen/native/transformers/cuda/flash_attn/flash_api.cpp",
]

# Files using thrust::sort_by_key need to be linked last
aten_cuda_with_sort_by_key_source_list = [
    # empty_cuda is needed by smith_cuda_cpp
    "aten/src/ATen/native/cuda/TensorFactories.cu",
]

aten_cuda_cu_with_sort_by_key_source_list = [
    "aten/src/ATen/native/cuda/Unique.cu",
]

# Following are source code for xnnpack delegate

xnnpack_delegate_serializer_header = [
    "smith/csrc/jit/backends/xnnpack/serialization/serializer.h",
]

xnnpack_delegate_serializer_source_list = [
    "smith/csrc/jit/backends/xnnpack/serialization/serializer.cpp",
]

xnnpack_delegate_core_source_list = [
    "smith/csrc/jit/backends/xnnpack/compiler/xnn_compiler.cpp",
]

xnnpack_delegate_core_header = [
    "smith/csrc/jit/backends/xnnpack/compiler/xnn_compiler.h",
    "smith/csrc/jit/backends/xnnpack/executor/xnn_executor.h",
]

xnnpack_backend_header = [
    "smith/csrc/jit/backends/xnnpack/xnnpack_graph_builder.h",
] + xnnpack_delegate_core_header

xnnpack_backend_source_list = [
    "smith/csrc/jit/backends/xnnpack/compiler/xnn_compiler.cpp",
    "smith/csrc/jit/backends/xnnpack/xnnpack_backend_lib.cpp",
    "smith/csrc/jit/backends/xnnpack/xnnpack_backend_preprocess.cpp",
    "smith/csrc/jit/backends/xnnpack/xnnpack_graph_builder.cpp",
] + xnnpack_delegate_core_source_list
