[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "coverage-plugins"
version = "0.0.1"
description = "Plug-in to coverage for Blacksmith JIT"
readme = "README.md"
license = "MIT"
authors = [{ name = "Blacksmith Team", email = "packages@blacksmith.org" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Repository = "https://github.com/blacksmith/blacksmith"
"Issue Tracker" = "https://github.com/blacksmith/blacksmith/issues"

[tool.setuptools.packages.find]
where = ["src"]
