if(WIN32)
  set(SMITH_PYTHON_IMPORTED_LOCATION "${BLACKSMITH_INSTALL_DIR}/lib/${CMAKE_IMPORT_LIBRARY_PREFIX}smith_python${CMAKE_IMPORT_LIBRARY_SUFFIX}")
else()
  set(SMITH_PYTHON_IMPORTED_LOCATION "${BLACKSMITH_INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}smith_python${CMAKE_SHARED_LIBRARY_SUFFIX}")
endif()

add_library(smith_python SHARED IMPORTED)

set_target_properties(smith_python PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${BLACKSMITH_INSTALL_DIR}/include"
  INTERFACE_LINK_LIBRARIES "c10;smith_cpu"
  IMPORTED_LOCATION "${SMITH_PYTHON_IMPORTED_LOCATION}"
)

add_library(smith_python_library INTERFACE IMPORTED)

set_target_properties(smith_python_library PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "\$<TARGET_PROPERTY:smith_python,INTERFACE_INCLUDE_DIRECTORIES>"
  INTERFACE_LINK_LIBRARIES "\$<TARGET_FILE:smith_python>;\$<TARGET_PROPERTY:smith_python,INTERFACE_LINK_LIBRARIES>"
)
